const express = require('express')
const auth = require('../middleware/auth')
const controller = require('../controllers/intelligenceController')

const router = express.Router()

const requireStudent = (req, res, next) => {
  if (req.user?.role !== 'student') {
    return res.status(403).json({ success: false, code: 'STUDENT_ONLY', message: 'Student intelligence access only.' })
  }
  return next()
}

router.get('/home', auth, requireStudent, controller.home)
router.get('/insights', auth, requireStudent, controller.insights)
router.get('/recommendations', auth, requireStudent, controller.recommendations)
router.get('/profile', auth, requireStudent, controller.getProfile)
router.put('/profile', auth, requireStudent, controller.updateProfile)
router.get('/memory', auth, requireStudent, controller.memory)
router.get('/learning-dashboard', auth, requireStudent, controller.learningDashboard)
router.get('/learning', auth, requireStudent, controller.learningIntelligence)
router.get('/learning/skill-gaps', auth, requireStudent, controller.learningSkillGaps)
router.get('/learning/next-action', auth, requireStudent, controller.learningNextAction)
router.get('/learning/adaptive', auth, requireStudent, controller.learningAdaptive)
router.get('/learning/progress-review', auth, requireStudent, controller.learningProgressReview)
router.get('/learning/resources', auth, requireStudent, controller.learningResources)
router.post('/learning/plan-suggestion', auth, requireStudent, controller.learningPlanSuggestion)
router.get('/daily-life', auth, requireStudent, controller.dailyLife)
router.get('/daily-life/next-action', auth, requireStudent, controller.dailyLifeNextAction)
router.get('/daily-life/plan', auth, requireStudent, controller.dailyLifePlan)
router.get('/daily-life/gaps', auth, requireStudent, controller.dailyLifeGaps)
router.get('/daily-life/risks', auth, requireStudent, controller.dailyLifeRisks)
router.post('/daily-life/breakdown', auth, requireStudent, controller.dailyLifeBreakdown)
router.post('/daily-life/actions/propose', auth, requireStudent, controller.dailyLifeProposeAction)
router.post('/daily-life/actions/confirm', auth, requireStudent, controller.dailyLifeConfirmAction)
router.get('/next-action', auth, requireStudent, controller.nextAction)
router.get('/decisions', auth, requireStudent, controller.decisionRecommendations)
router.get('/context-summary', auth, requireStudent, controller.contextSummary)
router.get('/graph/summary', auth, requireStudent, controller.graphSummary)
router.post('/recommendations/:fingerprint/dismiss', auth, requireStudent, controller.dismissRecommendation)
router.post('/recommendations/:fingerprint/feedback', auth, requireStudent, controller.feedbackRecommendation)

// Unified AI Brain (V4) — extends intelligence; does not replace mentor/agent
router.post('/brain/ask', auth, controller.brainAsk)
router.get('/brain/context', auth, controller.brainContext)
router.get('/brain/summary', auth, requireStudent, controller.brainSummary)
router.get('/brain/weekly', auth, requireStudent, controller.brainWeekly)
router.get('/brain/search', auth, requireStudent, controller.brainSearch)
router.post('/brain/search', auth, requireStudent, controller.brainSearch)
router.get('/brain/metrics', auth, controller.brainMetrics)

// Personal AI Operating Layer (V4 P3)
router.get('/personal', auth, requireStudent, controller.personalHome)
router.post('/personal/plan', auth, requireStudent, controller.personalPlan)
router.get('/personal/health', auth, requireStudent, controller.personalHealth)
router.get('/personal/proactive', auth, requireStudent, controller.personalProactive)
router.get('/personal/controls', auth, requireStudent, controller.personalControlsGet)
router.put('/personal/controls', auth, requireStudent, controller.personalControlsUpdate)

// Personal Knowledge Graph + Research Knowledge (V4 Prompt 4)
router.get('/knowledge', auth, requireStudent, controller.knowledgeCenter)
router.get('/knowledge/search', auth, requireStudent, controller.knowledgeSearch)
router.post('/knowledge/search', auth, requireStudent, controller.knowledgeSearch)
router.post('/knowledge/ask', auth, requireStudent, controller.knowledgeAsk)
router.get('/knowledge/map', auth, requireStudent, controller.knowledgeMap)
router.get('/knowledge/project/:projectId', auth, requireStudent, controller.knowledgeProjectMap)
router.get('/knowledge/goal/:goalId', auth, requireStudent, controller.knowledgeGoalMap)
router.get('/knowledge/edge/:edgeId', auth, requireStudent, controller.knowledgeExplain)
router.post('/knowledge/sync', auth, requireStudent, controller.knowledgeSync)
router.post('/knowledge/sources/:sourceId/process', auth, requireStudent, controller.knowledgeProcessSource)

// Continuous Intelligence + AI Command Center (V4 Prompt 8)
router.get('/command-center', auth, requireStudent, controller.commandCenter)
router.post('/command', auth, requireStudent, controller.aiCommand)
router.get('/command/history', auth, requireStudent, controller.commandHistory)
router.get('/continuous/insights', auth, requireStudent, controller.continuousInsights)
router.get('/continuous/progress', auth, requireStudent, controller.continuousProgress)
router.get('/continuous/daily', auth, requireStudent, controller.continuousDaily)
router.get('/continuous/weekly', auth, requireStudent, controller.continuousWeekly)
router.get('/continuous/context', auth, requireStudent, controller.continuousContext)
router.post('/continuous/decide', auth, requireStudent, controller.continuousDecide)
router.post('/continuous/events', auth, requireStudent, controller.continuousEvent)
router.get('/continuous/events', auth, requireStudent, controller.continuousEvents)
router.get('/continuous/decisions/:id', auth, requireStudent, controller.decisionGet)
router.post('/continuous/decisions/:id/override', auth, requireStudent, controller.decisionOverride)
router.post('/continuous/decisions/:id/feedback', auth, requireStudent, controller.decisionFeedback)

module.exports = router
