const express = require('express')
const router = express.Router()
const auth = require('../middleware/auth')
const requireRole = require('../middleware/requireRole')
const { resolveOrganization } = require('../middleware/resolveOrganization')
const partnershipController = require('../controllers/partnershipController')

const orgAuth = [auth, requireRole('institution', 'company'), resolveOrganization]
const intelCtrl = require('../controllers/partnershipIntelligenceController')

router.get('/collaboration/hub', orgAuth, intelCtrl.getHub)
router.get('/collaboration/feed', orgAuth, intelCtrl.getFeed)
router.get('/matches', orgAuth, intelCtrl.getMatches)
router.get('/analytics', orgAuth, intelCtrl.getAnalytics)
router.get('/ai/intents', orgAuth, intelCtrl.getAiIntents)
router.post('/ai/hub-insights', orgAuth, intelCtrl.getHubAiInsight)
router.post('/ai/proposal-draft', orgAuth, intelCtrl.buildProposalDraft)
router.get('/collaboration/dashboard', orgAuth, partnershipController.getCollaborationDashboard)
router.get('/meta', orgAuth, partnershipController.getMeta)
router.get('/stats', orgAuth, partnershipController.getStats)
router.get('/', orgAuth, partnershipController.listPartnerships)
router.post('/requests', orgAuth, partnershipController.createRequest)
router.get('/:id/brief', orgAuth, intelCtrl.getBrief)
router.get('/:id/renewal', orgAuth, intelCtrl.getRenewal)
router.get('/:id/workspace', orgAuth, partnershipController.getWorkspace)
router.patch('/:id/scope', orgAuth, partnershipController.updateScope)
router.post('/:id/pause', orgAuth, partnershipController.pausePartnership)
router.post('/:id/cancel', orgAuth, partnershipController.cancelPartnership)
router.post('/:id/accept', orgAuth, partnershipController.acceptPartnership)
router.post('/:id/reject', orgAuth, partnershipController.rejectPartnership)
router.post('/:id/links/:entityType/:entityId', orgAuth, partnershipController.linkEntity)
router.delete('/:id/links/:entityType/:entityId', orgAuth, partnershipController.unlinkEntity)
router.post('/:id/ai/insights', orgAuth, partnershipController.getAiInsights)
router.get('/:id', orgAuth, partnershipController.getPartnership)
router.patch('/:id', orgAuth, partnershipController.updatePartnership)
router.post('/:id/respond', orgAuth, partnershipController.respondToRequest)
router.get('/:id/activity', orgAuth, partnershipController.getActivity)
router.get('/:id/documents', orgAuth, partnershipController.listDocuments)
router.post('/:id/documents', orgAuth, partnershipController.addDocument)

module.exports = router
