/**
 * Future Agent Type Definitions — Sprint 6 Enterprise Edition
 * @module mj/agents/definitions/AgentTypes
 */

const { AGENT_TYPES } = require('../../constants')

const AGENT_DEFINITIONS = {
  [AGENT_TYPES.DEVELOPER]: {
    name: 'Developer Agent',
    description: 'Full-stack development, debugging, and architecture',
    capabilities: ['code', 'debug', 'refactor', 'architecture'],
    supportedTasks: ['coding', 'development', 'debugging'],
    priority: 8,
  },
  [AGENT_TYPES.BACKEND]: {
    name: 'Backend Agent',
    description: 'API, database, and server-side engineering',
    capabilities: ['api', 'database', 'server', 'microservices'],
    supportedTasks: ['coding', 'backend'],
    priority: 7,
  },
  [AGENT_TYPES.FRONTEND]: {
    name: 'Frontend Agent',
    description: 'UI implementation, React, and client-side engineering',
    capabilities: ['ui', 'react', 'css', 'ux'],
    supportedTasks: ['coding', 'frontend'],
    priority: 7,
  },
  [AGENT_TYPES.DESIGNER]: {
    name: 'UI/UX Designer Agent',
    description: 'Visual design, UX patterns, and branding',
    capabilities: ['design', 'figma', 'branding', 'visual', 'ux'],
    supportedTasks: ['design', 'ui'],
    priority: 6,
  },
  [AGENT_TYPES.THREEJS]: {
    name: 'Three.js Agent',
    description: '3D web graphics and Three.js development',
    capabilities: ['threejs', '3d', 'webgl', 'graphics'],
    supportedTasks: ['coding', '3d'],
    priority: 6,
  },
  [AGENT_TYPES.ANIMATION]: {
    name: 'Animation Agent',
    description: 'Motion design and animation systems',
    capabilities: ['animation', '3d', 'motion', 'timeline'],
    supportedTasks: ['design', 'animation'],
    priority: 5,
  },
  [AGENT_TYPES.RESEARCH]: {
    name: 'Research Agent',
    description: 'Deep research, analysis, and source synthesis',
    capabilities: ['research', 'analysis', 'summarize', 'sources'],
    supportedTasks: ['research'],
    priority: 8,
  },
  [AGENT_TYPES.LEARNING]: {
    name: 'Learning Agent',
    description: 'Learning paths, skill assessment, and progress tracking',
    capabilities: ['learning', 'curriculum', 'assessment', 'progress'],
    supportedTasks: ['learning', 'education'],
    priority: 6,
  },
  [AGENT_TYPES.TEACHER]: {
    name: 'Teacher Agent',
    description: 'Teaching, explanation, and quiz generation',
    capabilities: ['teach', 'explain', 'quiz', 'curriculum'],
    supportedTasks: ['learning', 'education'],
    priority: 7,
  },
  [AGENT_TYPES.RESUME]: {
    name: 'Resume Agent',
    description: 'Resume writing, career documents, and profile optimization',
    capabilities: ['resume', 'career', 'cv', 'profile'],
    supportedTasks: ['writing', 'career'],
    priority: 5,
  },
  [AGENT_TYPES.MARKETING]: {
    name: 'Marketing Agent',
    description: 'Marketing strategy, campaigns, and content planning',
    capabilities: ['marketing', 'content', 'campaigns', 'strategy'],
    supportedTasks: ['marketing'],
    priority: 6,
  },
  [AGENT_TYPES.SEO]: {
    name: 'SEO Agent',
    description: 'Search engine optimization and content ranking',
    capabilities: ['seo', 'keywords', 'ranking', 'analytics'],
    supportedTasks: ['marketing', 'seo'],
    priority: 5,
  },
  [AGENT_TYPES.BUSINESS]: {
    name: 'Business Strategy Agent',
    description: 'Business planning, operations, and strategy',
    capabilities: ['strategy', 'planning', 'operations', 'business'],
    supportedTasks: ['business'],
    priority: 7,
  },
  [AGENT_TYPES.FINANCE]: {
    name: 'Finance Agent',
    description: 'Financial analysis, budgeting, and forecasting',
    capabilities: ['finance', 'budget', 'forecasting', 'analysis'],
    supportedTasks: ['finance', 'business'],
    priority: 6,
  },
  [AGENT_TYPES.LEGAL]: {
    name: 'Legal Knowledge Agent',
    description: 'Legal information, compliance, and contract review',
    capabilities: ['legal', 'compliance', 'contracts', 'regulations'],
    supportedTasks: ['legal'],
    priority: 5,
  },
  [AGENT_TYPES.HEALTH]: {
    name: 'Health Advisor Agent',
    description: 'Wellness guidance and health information',
    capabilities: ['health', 'wellness', 'fitness', 'nutrition'],
    supportedTasks: ['health'],
    priority: 4,
  },
  [AGENT_TYPES.SECURITY]: {
    name: 'Security Assistant Agent',
    description: 'Security analysis, audit, and best practices',
    capabilities: ['security', 'audit', 'penetration', 'compliance'],
    supportedTasks: ['security'],
    priority: 7,
  },
  [AGENT_TYPES.DEPLOYMENT]: {
    name: 'Deployment Agent',
    description: 'CI/CD, infrastructure, and release management',
    capabilities: ['deploy', 'ci_cd', 'infrastructure', 'release'],
    supportedTasks: ['deployment', 'devops'],
    priority: 6,
  },
  [AGENT_TYPES.TESTING]: {
    name: 'Testing Agent',
    description: 'QA, test automation, and quality assurance',
    capabilities: ['testing', 'qa', 'e2e', 'unit_tests'],
    supportedTasks: ['testing', 'coding'],
    priority: 6,
  },
  [AGENT_TYPES.DOCUMENTATION]: {
    name: 'Documentation Agent',
    description: 'Technical docs, API references, and guides',
    capabilities: ['docs', 'api_docs', 'guides', 'technical_writing'],
    supportedTasks: ['documentation', 'writing'],
    priority: 5,
  },
  [AGENT_TYPES.TRANSLATION]: {
    name: 'Translation Agent',
    description: 'Multi-language translation and localization',
    capabilities: ['translation', 'localization', 'languages'],
    supportedTasks: ['translation', 'writing'],
    priority: 5,
  },
  [AGENT_TYPES.RD_REPORT]: {
    name: 'R&D Report Agent',
    description: 'Research reports, whitepapers, and technical analysis',
    capabilities: ['research', 'reports', 'analysis', 'whitepapers'],
    supportedTasks: ['research', 'writing'],
    priority: 6,
  },
  [AGENT_TYPES.CONTENT_WRITER]: {
    name: 'Content Writer Agent',
    description: 'Blog posts, articles, and creative content',
    capabilities: ['writing', 'content', 'articles', 'copywriting'],
    supportedTasks: ['writing', 'marketing'],
    priority: 6,
  },
  [AGENT_TYPES.PROMPT_ENGINEERING]: {
    name: 'Prompt Engineering Agent',
    description: 'AI prompt design, optimization, and evaluation',
    capabilities: ['prompts', 'ai', 'optimization', 'evaluation'],
    supportedTasks: ['coding', 'ai'],
    priority: 7,
  },
  [AGENT_TYPES.DATA_ANALYSIS]: {
    name: 'Data Analysis Agent',
    description: 'Data analysis, insights, and visualization guidance',
    capabilities: ['data', 'analysis', 'statistics', 'insights'],
    supportedTasks: ['research', 'analysis'],
    priority: 7,
  },
  [AGENT_TYPES.VIDEO]: {
    name: 'Video Agent',
    description: 'Video content planning and editing guidance',
    capabilities: ['video', 'editing', 'generation', 'storyboard'],
    supportedTasks: ['design', 'media'],
    priority: 5,
  },
  [AGENT_TYPES.AUTOMATION]: {
    name: 'Automation Agent',
    description: 'Workflow automation design (architecture only)',
    capabilities: ['automation', 'workflows', 'integration'],
    supportedTasks: ['automation'],
    priority: 5,
  },
  [AGENT_TYPES.MOBILE]: {
    name: 'Future Mobile Agent',
    description: 'Mobile app development (future sprint)',
    capabilities: ['mobile', 'ios', 'android', 'react_native'],
    supportedTasks: ['coding', 'mobile'],
    priority: 4,
  },
  [AGENT_TYPES.DESKTOP]: {
    name: 'Future Desktop Agent',
    description: 'Desktop application development (future sprint)',
    capabilities: ['desktop', 'electron', 'native'],
    supportedTasks: ['coding', 'desktop'],
    priority: 4,
  },
  [AGENT_TYPES.ROBOTICS]: {
    name: 'Future Robotics Agent',
    description: 'Robotics and IoT systems (future sprint)',
    capabilities: ['robotics', 'iot', 'hardware'],
    supportedTasks: ['robotics'],
    priority: 3,
  },
}

module.exports = { AGENT_DEFINITIONS, AGENT_TYPES }
