const mongoose = require('mongoose');

const companyProfileSchema = new mongoose.Schema({
  ownerId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true, index: true },
  slug: { type: String, unique: true, sparse: true, trim: true },
  name: { type: String, required: true, trim: true },
  status: { type: String, enum: ['pending', 'approved', 'suspended'], default: 'approved', index: true },
  verified: { type: Boolean, default: true },
  logo: { type: String, default: '' },
  banner: { type: String, default: '' },
  about: { type: String, default: '' },
  mission: { type: String, default: '' },
  vision: { type: String, default: '' },
  history: { type: String, default: '' },
  founderMessage: { type: String, default: '' },
  ceoMessage: { type: String, default: '' },
  culture: { type: String, default: '' },
  businessType: { type: String, default: '' },
  industry: { type: String, default: '', index: true },
  companySize: { type: String, enum: ['1-10', '11-50', '51-200', '201-500', '501-1000', '1000+', ''], default: '' },
  foundedYear: { type: Number, default: null },
  products: [{ name: String, description: String, url: String }],
  services: [{ name: String, description: String }],
  projectsShowcase: [{ name: String, description: String, url: String }],
  caseStudies: [{ title: String, summary: String, outcome: String, url: String }],
  techStack: [{ type: String }],
  awards: [{ title: String, year: String }],
  certifications: [{ title: String, issuer: String, year: String }],
  achievements: [{ title: String, description: String }],
  offices: [{ city: String, country: String, address: String }],
  branches: [{ name: String, city: String, address: String }],
  officeTour: { type: String, default: '' },
  careers: {
    overview: { type: String, default: '' },
    whyJoin: { type: String, default: '' },
    benefits: { type: String, default: '' },
    learningPrograms: { type: String, default: '' },
    training: { type: String, default: '' },
    employeeGrowth: { type: String, default: '' },
    promotionPolicy: { type: String, default: '' },
  },
  contact: {
    email: String,
    phone: String,
    website: String,
    linkedin: String,
    address: String,
    city: String,
    state: String,
    country: String,
  },
  social: {
    linkedin: String,
    twitter: String,
    facebook: String,
    instagram: String,
    youtube: String,
  },
  stats: {
    employeeCount: { type: Number, default: 0 },
    jobOpenings: { type: Number, default: 0 },
    internshipCount: { type: Number, default: 0 },
    followers: { type: Number, default: 0 },
    applications: { type: Number, default: 0 },
    hiringRate: { type: Number, default: 0 },
    visitors: { type: Number, default: 0 },
    aiScore: { type: Number, default: 0 },
    aiRating: { type: Number, default: 0 },
    industryRank: { type: Number, default: null },
    jobViews: { type: Number, default: 0 },
    internshipViews: { type: Number, default: 0 },
    websiteClicks: { type: Number, default: 0 },
    interviewsScheduled: { type: Number, default: 0 },
    offersReleased: { type: Number, default: 0 },
    studentEngagement: { type: Number, default: 0 },
    avgSalary: { type: Number, default: 0 },
  },
  aiInsights: {
    companyGrowth: String,
    hiringTrends: String,
    popularSkills: [String],
    futureHiring: String,
    technologyTrends: String,
    salaryTrends: String,
    careerGrowth: String,
    aiCompanyRating: Number,
    industryRanking: String,
    summary: String,
    generatedAt: Date,
  },
  isPublic: { type: Boolean, default: true },
}, { timestamps: true });

companyProfileSchema.index({ name: 'text', about: 'text', industry: 'text', techStack: 'text' });
companyProfileSchema.index({ 'contact.city': 1, industry: 1, companySize: 1 });

module.exports = mongoose.model('CompanyProfile', companyProfileSchema);
