import type { AcademicState } from "@/types/academic-management";

export const ACADEMIC_SEED: AcademicState = {
  departments: [
    {
      id: "dept-cse",
      name: "Computer Science",
      code: "CSE",
      logoInitials: "CS",
      description: "Computing, software engineering, and applied AI programs.",
      hod: "Dr. Meera Rao",
      vision: "Shape technology leaders for a digital society.",
      mission: "Deliver rigorous, industry-aligned computing education.",
      facultyCount: 24,
      studentCount: 640,
      status: "active",
    },
    {
      id: "dept-bba",
      name: "Business Administration",
      code: "BBA",
      logoInitials: "BA",
      description: "Management, leadership, and digital business programs.",
      hod: "Prof. Arjun Nair",
      vision: "Develop principled, future-ready business leaders.",
      mission: "Blend management theory with real enterprise practice.",
      facultyCount: 16,
      studentCount: 410,
      status: "active",
    },
    {
      id: "dept-des",
      name: "Design Studies",
      code: "DES",
      logoInitials: "DS",
      description: "Human-centered, interaction, and service design.",
      hod: "Ananya Iyer",
      vision: "Advance creative problem solving through design.",
      mission: "Prepare designers for meaningful product impact.",
      facultyCount: 9,
      studentCount: 180,
      status: "active",
    },
    {
      id: "dept-sci",
      name: "Applied Sciences",
      code: "SCI",
      logoInitials: "AS",
      description: "Foundational sciences and interdisciplinary research.",
      hod: "Dr. Neha Kapoor",
      vision: "Strengthen scientific foundations across disciplines.",
      mission: "Enable inquiry-led scientific learning.",
      facultyCount: 11,
      studentCount: 220,
      status: "draft",
    },
  ],
  programs: [
    {
      id: "prog-btech-cse",
      name: "B.Tech Computer Science",
      level: "undergraduate",
      duration: "4 years",
      credits: 160,
      eligibility: "10+2 with Mathematics",
      departmentId: "dept-cse",
      status: "active",
    },
    {
      id: "prog-mtech-cse",
      name: "M.Tech Data Science",
      level: "postgraduate",
      duration: "2 years",
      credits: 96,
      eligibility: "Bachelor's in relevant discipline",
      departmentId: "dept-cse",
      status: "active",
    },
    {
      id: "prog-mba",
      name: "MBA Digital Leadership",
      level: "postgraduate",
      duration: "2 years",
      credits: 88,
      eligibility: "Bachelor's degree with entrance test",
      departmentId: "dept-bba",
      status: "active",
    },
    {
      id: "prog-bba",
      name: "BBA Digital Business",
      level: "undergraduate",
      duration: "3 years",
      credits: 132,
      eligibility: "10+2 in any stream",
      departmentId: "dept-bba",
      status: "active",
    },
    {
      id: "prog-dip-ux",
      name: "UX Design Diploma",
      level: "diploma",
      duration: "1 year",
      credits: 48,
      eligibility: "10+2 in any stream",
      departmentId: "dept-des",
      status: "active",
    },
    {
      id: "prog-cert-ds",
      name: "Data Science Certificate",
      level: "certificate",
      duration: "6 months",
      credits: 24,
      eligibility: "Basic programming knowledge",
      departmentId: "dept-cse",
      status: "active",
    },
    {
      id: "prog-boot-fs",
      name: "Full-Stack Engineering Bootcamp",
      level: "bootcamp",
      duration: "5 months",
      credits: 20,
      eligibility: "Aptitude assessment",
      departmentId: "dept-cse",
      status: "draft",
    },
  ],
  courses: [
    {
      id: "crs-ds",
      name: "Data Structures",
      code: "CSE201",
      departmentId: "dept-cse",
      semester: "Semester 3",
      credits: 4,
      theoryHours: 3,
      practicalHours: 2,
      facultyAssigned: "Karan Deshmukh",
      prerequisites: "Programming Fundamentals",
      status: "active",
    },
    {
      id: "crs-cloud",
      name: "Cloud Architecture",
      code: "CSE402",
      departmentId: "dept-cse",
      semester: "Semester 7",
      credits: 3,
      theoryHours: 3,
      practicalHours: 0,
      facultyAssigned: "Dr. Vivek Reddy",
      prerequisites: "Operating Systems",
      status: "active",
    },
    {
      id: "crs-ob",
      name: "Organizational Behaviour",
      code: "BBA210",
      departmentId: "dept-bba",
      semester: "Semester 4",
      credits: 3,
      theoryHours: 3,
      practicalHours: 0,
      facultyAssigned: "Dr. Neha Kapoor",
      prerequisites: "Principles of Management",
      status: "active",
    },
    {
      id: "crs-strategy",
      name: "Digital Strategy",
      code: "MBA110",
      departmentId: "dept-bba",
      semester: "Semester 1",
      credits: 4,
      theoryHours: 3,
      practicalHours: 1,
      facultyAssigned: "Prof. Arjun Nair",
      prerequisites: "None",
      status: "active",
    },
    {
      id: "crs-ixd",
      name: "Interaction Design",
      code: "DES101",
      departmentId: "dept-des",
      semester: "Semester 1",
      credits: 4,
      theoryHours: 2,
      practicalHours: 3,
      facultyAssigned: "Ananya Iyer",
      prerequisites: "Design Thinking",
      status: "active",
    },
    {
      id: "crs-ml",
      name: "Applied Machine Learning",
      code: "CSE305",
      departmentId: "dept-cse",
      semester: "Semester 5",
      credits: 4,
      theoryHours: 3,
      practicalHours: 2,
      facultyAssigned: "Dr. Priya Shah",
      prerequisites: "Statistics, Python",
      status: "draft",
    },
  ],
  subjects: [
    {
      id: "sub-algo",
      name: "Algorithms",
      code: "CSE202",
      semester: "Semester 3",
      credits: 4,
      faculty: "Karan Deshmukh",
      labRequired: true,
      elective: false,
      description: "Design and analysis of algorithms with lab practice.",
    },
    {
      id: "sub-dbms",
      name: "Database Systems",
      code: "CSE204",
      semester: "Semester 4",
      credits: 4,
      faculty: "Dr. Priya Shah",
      labRequired: true,
      elective: false,
      description: "Relational modeling, SQL, and transactions.",
    },
    {
      id: "sub-ai",
      name: "Artificial Intelligence",
      code: "CSE306",
      semester: "Semester 6",
      credits: 3,
      faculty: "Dr. Meera Rao",
      labRequired: false,
      elective: true,
      description: "Foundations of intelligent systems.",
    },
    {
      id: "sub-mktg",
      name: "Marketing Analytics",
      code: "BBA212",
      semester: "Semester 4",
      credits: 3,
      faculty: "Fatima Ali",
      labRequired: false,
      elective: true,
      description: "Data-driven marketing decision making.",
    },
    {
      id: "sub-vis",
      name: "Design Visualization",
      code: "DES103",
      semester: "Semester 2",
      credits: 4,
      faculty: "Rohit Bose",
      labRequired: true,
      elective: false,
      description: "Visual communication and prototyping.",
    },
  ],
  semesters: [
    {
      id: "sem-1",
      number: 1,
      academicYear: "2026-27",
      duration: "6 months",
      startDate: "2026-07-01",
      endDate: "2026-12-15",
      subjectsIncluded: 6,
      credits: 22,
      status: "active",
    },
    {
      id: "sem-2",
      number: 2,
      academicYear: "2026-27",
      duration: "6 months",
      startDate: "2027-01-05",
      endDate: "2027-06-10",
      subjectsIncluded: 6,
      credits: 24,
      status: "draft",
    },
    {
      id: "sem-3",
      number: 3,
      academicYear: "2025-26",
      duration: "6 months",
      startDate: "2025-07-01",
      endDate: "2025-12-15",
      subjectsIncluded: 7,
      credits: 26,
      status: "inactive",
    },
  ],
  curriculum: [
    { id: "cur-1", semester: "Semester 1", subject: "Design Thinking", type: "core", credits: 4 },
    { id: "cur-2", semester: "Semester 1", subject: "Programming Fundamentals", type: "core", credits: 4 },
    { id: "cur-3", semester: "Semester 2", subject: "Design Visualization", type: "lab", credits: 4 },
    { id: "cur-4", semester: "Semester 3", subject: "Algorithms", type: "lab", credits: 4 },
    { id: "cur-5", semester: "Semester 4", subject: "Marketing Analytics", type: "elective", credits: 3 },
    { id: "cur-6", semester: "Semester 6", subject: "Capstone Project", type: "project", credits: 6 },
    { id: "cur-7", semester: "Semester 7", subject: "Industry Internship", type: "internship", credits: 8 },
  ],
  calendar: [
    { id: "cal-1", title: "Odd semester begins", type: "semester-start", date: "2026-07-01", academicYear: "2026-27" },
    { id: "cal-2", title: "Internal assessment I", type: "internal-exam", date: "2026-08-24", academicYear: "2026-27" },
    { id: "cal-3", title: "Design systems workshop", type: "workshop", date: "2026-09-10", academicYear: "2026-27" },
    { id: "cal-4", title: "Assignment submission window", type: "assignment", date: "2026-10-05", academicYear: "2026-27" },
    { id: "cal-5", title: "Regional holiday", type: "holiday", date: "2026-08-17", academicYear: "2026-27" },
    { id: "cal-6", title: "End semester examinations", type: "examination", date: "2026-11-25", academicYear: "2026-27" },
    { id: "cal-7", title: "Odd semester ends", type: "semester-end", date: "2026-12-15", academicYear: "2026-27" },
    { id: "cal-8", title: "Annual technology symposium", type: "event", date: "2026-07-24", academicYear: "2026-27" },
  ],
};
