import type { CampusState } from "@/types/campus-management";

export const CAMPUS_SEED: CampusState = {
  announcements: [
    {
      id: "ann-1",
      title: "End Semester Examination Schedule Released",
      body: "The odd semester examination timetable is now published. Review your schedule and reporting times on the student portal.",
      category: "examination",
      priority: "high",
      audience: "students",
      pinned: true,
      publishAt: "2026-07-15",
      expiryAt: "2026-11-30",
      status: "published",
      attachments: ["exam-timetable.pdf"],
      views: 1284,
    },
    {
      id: "ann-2",
      title: "Nimbus Cloud Labs Campus Drive",
      body: "Nimbus Cloud Labs will conduct a hybrid campus drive. Eligible students must register before the deadline.",
      category: "placement",
      priority: "high",
      audience: "students",
      pinned: true,
      publishAt: "2026-07-16",
      expiryAt: "2026-08-12",
      status: "published",
      attachments: [],
      views: 942,
    },
    {
      id: "ann-3",
      title: "Independence Day Holiday",
      body: "The institution will remain closed on August 15 in observance of Independence Day.",
      category: "holiday",
      priority: "medium",
      audience: "institution",
      pinned: false,
      publishAt: "2026-08-01",
      expiryAt: "2026-08-16",
      status: "scheduled",
      attachments: [],
      views: 210,
    },
    {
      id: "ann-4",
      title: "Fire Drill — Emergency Preparedness",
      body: "A campus-wide fire drill will be conducted. Please follow marshal instructions and assemble at designated points.",
      category: "emergency",
      priority: "high",
      audience: "institution",
      pinned: false,
      publishAt: "2026-07-20",
      expiryAt: "2026-07-21",
      status: "published",
      attachments: [],
      views: 655,
    },
    {
      id: "ann-5",
      title: "New Academic Resources Portal",
      body: "A refreshed academic resources portal is available with lecture notes, references, and lab manuals.",
      category: "academic",
      priority: "low",
      audience: "students",
      pinned: false,
      publishAt: "2026-07-10",
      expiryAt: "2026-09-30",
      status: "published",
      attachments: ["resources-guide.pdf"],
      views: 388,
    },
  ],
  events: [
    {
      id: "evt-1",
      title: "AI & ML Hands-on Workshop",
      description: "A practical workshop covering applied machine learning with real datasets and deployment.",
      category: "workshop",
      bannerInitials: "AI",
      date: "2026-07-24",
      time: "10:00",
      venue: "Innovation Lab",
      mode: "offline",
      capacity: 120,
      registered: 96,
      registrationDeadline: "2026-07-22",
      organizer: "AI Club",
      department: "Computer Science",
      guestSpeakers: ["Dr. Priya Shah"],
      agenda: ["Foundations", "Model building", "Deployment", "Q&A"],
      status: "upcoming",
    },
    {
      id: "evt-2",
      title: "Dream Wave Hackathon 2026",
      description: "A 24-hour hackathon challenging students to build impactful products across tracks.",
      category: "hackathon",
      bannerInitials: "HK",
      date: "2026-08-09",
      time: "09:00",
      venue: "Central Auditorium / Online",
      mode: "hybrid",
      capacity: 300,
      registered: 214,
      registrationDeadline: "2026-08-05",
      organizer: "Coding Club",
      department: "Computer Science",
      guestSpeakers: ["Sanjana Rao", "Rohan Mehta"],
      agenda: ["Kickoff", "Build sprint", "Mentoring", "Judging"],
      status: "upcoming",
    },
    {
      id: "evt-3",
      title: "Annual Cultural Fest — Rhythm",
      description: "Three days of music, dance, drama, and art celebrating campus creativity.",
      category: "festival",
      bannerInitials: "RH",
      date: "2026-07-18",
      time: "16:00",
      venue: "Open Air Theatre",
      mode: "offline",
      capacity: 1000,
      registered: 640,
      registrationDeadline: "2026-07-16",
      organizer: "Cultural Club",
      department: "All Departments",
      guestSpeakers: [],
      agenda: ["Inauguration", "Performances", "Prize distribution"],
      status: "ongoing",
    },
    {
      id: "evt-4",
      title: "Leadership Seminar",
      description: "A guest seminar on modern leadership and career acceleration.",
      category: "seminar",
      bannerInitials: "LS",
      date: "2026-06-28",
      time: "11:00",
      venue: "Seminar Hall B",
      mode: "offline",
      capacity: 200,
      registered: 180,
      registrationDeadline: "2026-06-26",
      organizer: "Entrepreneurship Club",
      department: "Business Administration",
      guestSpeakers: ["Prof. Arjun Nair"],
      agenda: ["Keynote", "Panel", "Networking"],
      status: "completed",
    },
    {
      id: "evt-5",
      title: "Inter-College Sports Meet",
      description: "Track, field, and team sports championship across partner institutions.",
      category: "sports",
      bannerInitials: "SM",
      date: "2026-08-16",
      time: "08:00",
      venue: "Sports Complex",
      mode: "offline",
      capacity: 500,
      registered: 132,
      registrationDeadline: "2026-08-10",
      organizer: "Sports Club",
      department: "All Departments",
      guestSpeakers: [],
      agenda: ["Opening ceremony", "Heats", "Finals"],
      status: "upcoming",
    },
  ],
  clubs: [
    { id: "club-ai", name: "AI Club", category: "ai", logoInitials: "AI", coordinator: "Dr. Meera Rao", president: "Aarav Sharma", members: 148, upcomingActivities: ["AI Workshop", "Paper reading"], status: "active" },
    { id: "club-code", name: "Coding Club", category: "coding", logoInitials: "CC", coordinator: "Karan Deshmukh", president: "Diya Patel", members: 212, upcomingActivities: ["Hackathon", "DSA sprint"], status: "active" },
    { id: "club-robo", name: "Robotics Club", category: "robotics", logoInitials: "RB", coordinator: "Dr. Vivek Reddy", president: "Ishaan Verma", members: 86, upcomingActivities: ["Line follower build"], status: "active" },
    { id: "club-cult", name: "Cultural Club", category: "cultural", logoInitials: "CL", coordinator: "Ananya Iyer", president: "Sara Khan", members: 320, upcomingActivities: ["Rhythm Fest"], status: "active" },
    { id: "club-music", name: "Music Club", category: "music", logoInitials: "MU", coordinator: "Rohit Bose", president: "Kabir Singh", members: 95, upcomingActivities: ["Open mic"], status: "active" },
    { id: "club-photo", name: "Photography Club", category: "photography", logoInitials: "PH", coordinator: "Fatima Ali", president: "Meera Nair", members: 74, upcomingActivities: ["Campus photowalk"], status: "active" },
    { id: "club-ent", name: "Entrepreneurship Club", category: "entrepreneurship", logoInitials: "EN", coordinator: "Prof. Arjun Nair", president: "Vivaan Reddy", members: 118, upcomingActivities: ["Startup pitch day"], status: "active" },
    { id: "club-sports", name: "Sports Club", category: "sports", logoInitials: "SP", coordinator: "Dr. Neha Kapoor", president: "Aditya Rao", members: 260, upcomingActivities: ["Sports Meet"], status: "active" },
  ],
  albums: [
    { id: "alb-1", title: "Convocation 2025", category: "convocation", coverInitials: "CV", photos: 184, videos: 6, date: "2025-12-20", description: "Graduation ceremony highlights and moments." },
    { id: "alb-2", title: "Rhythm Cultural Fest", category: "festivals", coverInitials: "RH", photos: 342, videos: 14, date: "2026-07-18", description: "Cultural festival performances and celebrations." },
    { id: "alb-3", title: "Annual Sports Meet", category: "sports", coverInitials: "SM", photos: 256, videos: 9, date: "2026-02-11", description: "Athletics and team sports championship." },
    { id: "alb-4", title: "Placement Highlights", category: "placements", coverInitials: "PL", photos: 92, videos: 3, date: "2026-06-30", description: "Top recruiters and placed students." },
    { id: "alb-5", title: "AI Workshop Memories", category: "workshops", coverInitials: "AI", photos: 78, videos: 2, date: "2026-07-24", description: "Hands-on machine learning workshop." },
    { id: "alb-6", title: "National Award Ceremony", category: "achievements", coverInitials: "AW", photos: 54, videos: 1, date: "2026-05-15", description: "Institution and student achievements." },
  ],
  news: [
    { id: "news-1", title: "Institution ranked in national top 20", type: "ranking", summary: "Recognized for academic excellence and placements in the latest national rankings.", date: "2026-07-01", department: "Institution" },
    { id: "news-2", title: "Student team wins national hackathon", type: "student-achievement", summary: "Coding Club team secured first place at the national-level hackathon.", date: "2026-06-22", department: "Computer Science" },
    { id: "news-3", title: "Faculty research published in IEEE", type: "research", summary: "Applied AI research accepted at a leading IEEE conference.", date: "2026-06-10", department: "Computer Science" },
    { id: "news-4", title: "Record placement season", type: "placement", summary: "91% placement rate with the highest package to date.", date: "2026-06-30", department: "Placement Cell" },
    { id: "news-5", title: "Design student wins international award", type: "award", summary: "Recognized at an international design competition.", date: "2026-05-18", department: "Design Studies" },
    { id: "news-6", title: "Robotics team qualifies for finals", type: "competition", summary: "Robotics Club advanced to the national robotics championship finals.", date: "2026-07-05", department: "Computer Science" },
  ],
};
