import type { CommunityUserState } from "@/types/community";

export const COMMUNITY_ROUTES = {
  root: "/community",
  communities: "/community/communities",
  discussions: "/community/discussions",
  teams: "/community/teams",
  mentors: "/community/mentors",
  groups: "/community/groups",
  projects: "/community/projects",
  messages: "/community/messages",
} as const;

export const COMMUNITY_NAV = [
  { label: "Home", href: COMMUNITY_ROUTES.root },
  { label: "Communities", href: COMMUNITY_ROUTES.communities },
  { label: "Discussions", href: COMMUNITY_ROUTES.discussions },
  { label: "Teams", href: COMMUNITY_ROUTES.teams },
  { label: "Mentors", href: COMMUNITY_ROUTES.mentors },
  { label: "Study Groups", href: COMMUNITY_ROUTES.groups },
  { label: "Projects", href: COMMUNITY_ROUTES.projects },
  { label: "Messages", href: COMMUNITY_ROUTES.messages },
] as const;

const now = Date.now();

export const SEED_COMMUNITY: CommunityUserState = {
  communities: [
    {
      id: "com-public-ai",
      name: "AI Learners Hub",
      kind: "public",
      description: "Open discussions on applied AI for students.",
      members: 1840,
      topics: ["AI", "Prompting", "Projects"],
      trending: true,
      joined: true,
    },
    {
      id: "com-inst-cs",
      name: "Campus CS Circle",
      kind: "institution",
      description: "Institution community for CS cohorts and faculty.",
      members: 420,
      topics: ["Algorithms", "Systems"],
      joined: true,
    },
    {
      id: "com-co-nova",
      name: "Nova Labs Talent",
      kind: "company",
      description: "Company community for internships and hiring prep.",
      members: 260,
      topics: ["Careers", "Internships"],
      trending: true,
    },
    {
      id: "com-course-react",
      name: "React Mastery Cohort",
      kind: "course",
      description: "Course community for weekly React challenges.",
      members: 188,
      topics: ["React", "Frontend"],
      joined: false,
    },
    {
      id: "com-sub-math",
      name: "Applied Mathematics",
      kind: "subject",
      description: "Subject community for problem sets and tutoring.",
      members: 312,
      topics: ["Linear Algebra", "Probability"],
    },
    {
      id: "com-proj-capstone",
      name: "Capstone Builders",
      kind: "project",
      description: "Project community for team milestones and demos.",
      members: 96,
      topics: ["Product", "Delivery"],
      joined: true,
    },
  ],
  posts: [
    {
      id: "post-1",
      communityId: "com-public-ai",
      author: "Aisha Khan",
      title: "How are you structuring AI study notes?",
      body: "I am trying a weekly loop: concept summary → flashcards → mini project. What works for your cohort?",
      tags: ["study", "ai"],
      createdAt: new Date(now - 3600000).toISOString(),
      reactions: [
        { type: "like", count: 24 },
        { type: "insight", count: 8 },
        { type: "helpful", count: 11 },
      ],
      comments: [
        {
          id: "c-1",
          author: "Rohan Mehta",
          body: "Add a retrieval quiz on day 3. That locked concepts for me.",
          createdAt: new Date(now - 3000000).toISOString(),
          replies: [
            {
              id: "r-1",
              author: "Aisha Khan",
              body: "Great tip — trying that this week.",
              createdAt: new Date(now - 2800000).toISOString(),
            },
          ],
        },
      ],
      saved: false,
      aiSuggestions: [
        "Share your weekly template as a checklist.",
        "Ask peers for one project idea per concept.",
        "Offer a short study-group invite for accountability.",
      ],
    },
    {
      id: "post-2",
      communityId: "com-inst-cs",
      author: "Priya Nair",
      title: "Capstone milestone sync for Friday",
      body: "Looking for teammates who can review UX flows before demo day.",
      tags: ["capstone", "ux"],
      createdAt: new Date(now - 7200000).toISOString(),
      reactions: [
        { type: "like", count: 12 },
        { type: "helpful", count: 5 },
      ],
      comments: [],
      saved: true,
      aiSuggestions: [
        "Attach your Figma link and ask for specific feedback areas.",
        "Propose a 20-minute review slot.",
      ],
    },
  ],
  mentors: [
    {
      id: "men-1",
      name: "Dr. Meera Shah",
      title: "AI Systems Mentor",
      rating: 4.9,
      sessions: 128,
      specialties: ["Machine Learning", "Research Methods"],
      available: true,
    },
    {
      id: "men-2",
      name: "Arjun Desai",
      title: "Product Engineering Coach",
      rating: 4.8,
      sessions: 94,
      specialties: ["Frontend", "System Design"],
      available: true,
    },
    {
      id: "men-3",
      name: "Sara Ali",
      title: "Career Mentor",
      rating: 4.7,
      sessions: 76,
      specialties: ["Interviews", "Portfolio"],
      available: false,
    },
  ],
  groups: [
    {
      id: "grp-1",
      name: "DSA Evening Circle",
      subject: "Algorithms",
      members: ["You", "Aisha", "Rohan", "Neha"],
      progress: 62,
      nextSession: "Tomorrow · 7:00 PM",
      resources: ["LeetCode set A", "Pattern notes.pdf"],
    },
    {
      id: "grp-2",
      name: "Design Critique Pod",
      subject: "UX Design",
      members: ["You", "Priya", "Kabir"],
      progress: 44,
      nextSession: "Friday · 5:30 PM",
      resources: ["Heuristic checklist", "Case study template"],
    },
  ],
  teams: [
    {
      id: "team-1",
      name: "Pulse Learning Squad",
      focus: "Adaptive learning prototype",
      members: ["You", "Aisha", "Rohan", "Priya"],
      sharedNotes: ["User interview themes", "MVP scope v2"],
      sharedResources: ["Figma file", "API contract.md"],
      sharedTasks: [
        { id: "st-1", title: "Finalize onboarding flow", done: true },
        { id: "st-2", title: "Wire progress analytics", done: false },
        { id: "st-3", title: "Prep mentor demo script", done: false },
      ],
      roadmap: "Discovery → Prototype → Pilot → Showcase",
    },
  ],
  projects: [
    {
      id: "proj-1",
      title: "Adaptive Mentor Assistant",
      progress: 58,
      teamId: "team-1",
      milestones: [
        { id: "pm-1", label: "Research synthesis", done: true },
        { id: "pm-2", label: "Interactive prototype", done: true },
        { id: "pm-3", label: "Pilot with 10 students", done: false },
        { id: "pm-4", label: "Demo day presentation", done: false },
      ],
      documents: ["PRD.pdf", "Architecture notes.md", "Pilot plan.docx"],
      timeline: [
        {
          id: "pt-1",
          label: "Kickoff completed",
          at: new Date(now - 1209600000).toISOString(),
        },
        {
          id: "pt-2",
          label: "Prototype reviewed",
          at: new Date(now - 432000000).toISOString(),
        },
        {
          id: "pt-3",
          label: "Pilot recruitment started",
          at: new Date(now - 86400000).toISOString(),
        },
      ],
    },
  ],
  conversations: [
    {
      id: "conv-1",
      title: "Pulse Learning Squad",
      participants: ["You", "Aisha", "Rohan"],
      unread: 2,
      lastMessage: "Shared the updated roadmap link.",
      updatedAt: new Date(now - 1800000).toISOString(),
    },
    {
      id: "conv-2",
      title: "Dr. Meera Shah",
      participants: ["You", "Dr. Meera Shah"],
      unread: 0,
      lastMessage: "Looking forward to Thursday’s session.",
      updatedAt: new Date(now - 86400000).toISOString(),
    },
  ],
  messages: [
    {
      id: "msg-1",
      conversationId: "conv-1",
      from: "Aisha",
      body: "Shared the updated roadmap link.",
      at: new Date(now - 1800000).toISOString(),
      kind: "text",
    },
    {
      id: "msg-2",
      conversationId: "conv-1",
      from: "Rohan",
      body: "pilot-plan.pdf",
      at: new Date(now - 1700000).toISOString(),
      kind: "file",
      fileName: "pilot-plan.pdf",
    },
    {
      id: "msg-3",
      conversationId: "conv-2",
      from: "Dr. Meera Shah",
      body: "Looking forward to Thursday’s session.",
      at: new Date(now - 86400000).toISOString(),
      kind: "text",
    },
  ],
  activity: [
    {
      id: "act-1",
      label: "Joined Capstone Builders",
      at: new Date(now - 7200000).toISOString(),
      kind: "join",
    },
    {
      id: "act-2",
      label: "Commented on AI study notes thread",
      at: new Date(now - 3600000).toISOString(),
      kind: "post",
    },
    {
      id: "act-3",
      label: "Booked mentor session with Arjun Desai",
      at: new Date(now - 90000000).toISOString(),
      kind: "session",
    },
  ],
  bookedMentorIds: ["men-2"],
};
