import type { InstitutionState } from "@/types/institution";

function id(prefix: string, n: number) {
  return `${prefix}-${n}`;
}

export const INSTITUTION_SEED: InstitutionState = {
  profile: {
    name: "Dream Wave Academy",
    type: "college",
    code: "DWA-01",
    email: "admin@dreamwave.academy",
    phone: "+91 98765 43210",
    website: "https://dreamwave.academy",
    address: "12 Innovation Drive",
    city: "Hyderabad",
    state: "Telangana",
    country: "India",
    accreditation: "NAAC A+",
    establishedYear: "2014",
    description:
      "An AI-first learning institution preparing students for modern careers.",
  },
  settings: {
    timezone: "Asia/Kolkata",
    academicYear: "2025-26",
    allowSelfEnrollment: false,
    notifyParents: true,
    defaultLanguage: "en",
  },
  departments: [
    {
      id: id("dept", 1),
      name: "Computer Science",
      code: "CSE",
      head: "Dr. Meera Rao",
      status: "active",
      facultyCount: 18,
      studentCount: 420,
    },
    {
      id: id("dept", 2),
      name: "Business Administration",
      code: "BBA",
      head: "Prof. Arjun Nair",
      status: "active",
      facultyCount: 12,
      studentCount: 310,
    },
    {
      id: id("dept", 3),
      name: "Design Studies",
      code: "DES",
      head: "Ananya Iyer",
      status: "pending",
      facultyCount: 7,
      studentCount: 140,
    },
  ],
  branches: [
    {
      id: id("br", 1),
      name: "Main Campus",
      code: "MAIN",
      city: "Hyderabad",
      campus: "Central",
      status: "active",
    },
    {
      id: id("br", 2),
      name: "North Extension",
      code: "NORTH",
      city: "Secunderabad",
      campus: "North",
      status: "active",
    },
  ],
  courses: [
    {
      id: id("crs", 1),
      name: "B.Tech Computer Science",
      code: "BT-CSE",
      departmentId: id("dept", 1),
      duration: "4 years",
      level: "undergraduate",
      status: "active",
    },
    {
      id: id("crs", 2),
      name: "MBA Digital Leadership",
      code: "MBA-DL",
      departmentId: id("dept", 2),
      duration: "2 years",
      level: "postgraduate",
      status: "active",
    },
    {
      id: id("crs", 3),
      name: "UX Design Diploma",
      code: "DIP-UX",
      departmentId: id("dept", 3),
      duration: "1 year",
      level: "diploma",
      status: "active",
    },
  ],
  subjects: [
    {
      id: id("sub", 1),
      name: "Data Structures",
      code: "CSE201",
      courseId: id("crs", 1),
      credits: 4,
      semester: "Semester 3",
      status: "active",
    },
    {
      id: id("sub", 2),
      name: "Product Strategy",
      code: "MBA110",
      courseId: id("crs", 2),
      credits: 3,
      semester: "Term 1",
      status: "active",
    },
    {
      id: id("sub", 3),
      name: "Interaction Design",
      code: "DES101",
      courseId: id("crs", 3),
      credits: 4,
      semester: "Module A",
      status: "active",
    },
  ],
  teachers: [
    {
      id: id("tch", 1),
      name: "Dr. Meera Rao",
      email: "meera.rao@dreamwave.academy",
      departmentId: id("dept", 1),
      designation: "Head of Department",
      phone: "+91 90000 11111",
      status: "active",
    },
    {
      id: id("tch", 2),
      name: "Karan Deshmukh",
      email: "karan.d@dreamwave.academy",
      departmentId: id("dept", 1),
      designation: "Senior Lecturer",
      phone: "+91 90000 22222",
      status: "active",
    },
    {
      id: id("tch", 3),
      name: "Sana Qureshi",
      email: "sana.q@dreamwave.academy",
      departmentId: id("dept", 3),
      designation: "Faculty",
      phone: "+91 90000 33333",
      status: "inactive",
    },
  ],
  students: [
    {
      id: id("stu", 1),
      name: "Riya Patel",
      email: "riya.patel@student.dreamwave.academy",
      enrollmentId: "ENR-24001",
      courseId: id("crs", 1),
      year: "2",
      status: "active",
    },
    {
      id: id("stu", 2),
      name: "Mohammed Farhan",
      email: "farhan@student.dreamwave.academy",
      enrollmentId: "ENR-24018",
      courseId: id("crs", 2),
      year: "1",
      status: "active",
    },
    {
      id: id("stu", 3),
      name: "Emily Chen",
      email: "emily.chen@student.dreamwave.academy",
      enrollmentId: "ENR-24102",
      courseId: id("crs", 3),
      year: "1",
      status: "pending",
    },
  ],
  classes: [
    {
      id: id("cls", 1),
      name: "CSE-A Data Structures",
      courseId: id("crs", 1),
      teacherId: id("tch", 2),
      room: "Lab 204",
      schedule: "Mon/Wed 10:00–11:30",
      capacity: 40,
      enrolled: 36,
      status: "active",
    },
    {
      id: id("cls", 2),
      name: "MBA Cohort Alpha",
      courseId: id("crs", 2),
      teacherId: id("tch", 1),
      room: "Seminar 1",
      schedule: "Tue/Thu 14:00–15:30",
      capacity: 30,
      enrolled: 28,
      status: "active",
    },
  ],
  members: [
    {
      id: id("mem", 1),
      name: "Institution Admin",
      email: "admin@dreamwave.academy",
      role: "admin",
      departmentId: id("dept", 1),
      status: "active",
    },
    {
      id: id("mem", 2),
      name: "Coordinator West",
      email: "coord.west@dreamwave.academy",
      role: "coordinator",
      departmentId: id("dept", 2),
      status: "active",
    },
  ],
  notifications: [
    {
      id: id("ntf", 1),
      title: "New faculty onboarding pending",
      body: "3 teacher profiles await verification this week.",
      createdAt: new Date().toISOString(),
      read: false,
      category: "admin",
    },
    {
      id: id("ntf", 2),
      title: "Semester timetable published",
      body: "Academic year 2025-26 schedules are live for all departments.",
      createdAt: new Date(Date.now() - 86400000).toISOString(),
      read: true,
      category: "academic",
    },
    {
      id: id("ntf", 3),
      title: "Attendance sync completed",
      body: "Class attendance for the last 7 days has been synchronized.",
      createdAt: new Date(Date.now() - 172800000).toISOString(),
      read: false,
      category: "system",
    },
  ],
};
