import type { PlacementState } from "@/types/placement-management";

export const PLACEMENT_SEED: PlacementState = {
  recruiters: [
    {
      id: "rec-nimbus",
      logoInitials: "NB",
      name: "Nimbus Cloud Labs",
      industry: "Cloud & DevOps",
      hrContact: "Sanjana Rao",
      email: "careers@nimbuslabs.dev",
      phone: "+91 98450 22110",
      location: "Bengaluru, IN",
      website: "https://nimbuslabs.dev",
      about:
        "Nimbus Cloud Labs builds developer-first cloud infrastructure and reliability tooling for global enterprises.",
      hiringDepartments: ["Computer Science", "Applied Sciences"],
      requiredSkills: ["React", "Go", "Kubernetes", "AWS"],
      hiringProcess: ["Aptitude", "Technical", "System Design", "HR"],
      pastPlacements: 42,
      internshipsCount: 2,
      jobsCount: 2,
      driveStatus: "upcoming",
      status: "active",
    },
    {
      id: "rec-quant",
      logoInitials: "QF",
      name: "QuantFin Analytics",
      industry: "FinTech",
      hrContact: "Rohan Mehta",
      email: "talent@quantfin.io",
      phone: "+91 99870 41235",
      location: "Mumbai, IN",
      website: "https://quantfin.io",
      about:
        "QuantFin Analytics delivers quantitative trading and risk intelligence platforms for capital markets.",
      hiringDepartments: ["Computer Science", "Business Administration"],
      requiredSkills: ["Python", "SQL", "Statistics", "ML"],
      hiringProcess: ["Online Test", "Case Study", "Technical", "HR"],
      pastPlacements: 28,
      internshipsCount: 1,
      jobsCount: 1,
      driveStatus: "ongoing",
      status: "active",
    },
    {
      id: "rec-vertex",
      logoInitials: "VX",
      name: "Vertex Design Studio",
      industry: "Product Design",
      hrContact: "Ananya Iyer",
      email: "hello@vertex.design",
      phone: "+91 90080 55621",
      location: "Remote",
      website: "https://vertex.design",
      about:
        "Vertex Design Studio partners with product teams to craft human-centered digital experiences.",
      hiringDepartments: ["Design Studies"],
      requiredSkills: ["Figma", "UX Research", "Prototyping"],
      hiringProcess: ["Portfolio", "Design Challenge", "HR"],
      pastPlacements: 15,
      internshipsCount: 1,
      jobsCount: 1,
      driveStatus: "completed",
      status: "active",
    },
    {
      id: "rec-helix",
      logoInitials: "HX",
      name: "Helix Health Systems",
      industry: "HealthTech",
      hrContact: "Dr. Neha Kapoor",
      email: "recruit@helixhealth.com",
      phone: "+91 93450 77812",
      location: "Hyderabad, IN",
      website: "https://helixhealth.com",
      about:
        "Helix Health Systems builds clinical intelligence and patient engagement platforms.",
      hiringDepartments: ["Computer Science", "Applied Sciences"],
      requiredSkills: ["Java", "Spring", "Data Engineering"],
      hiringProcess: ["Aptitude", "Technical", "Managerial", "HR"],
      pastPlacements: 33,
      internshipsCount: 1,
      jobsCount: 1,
      driveStatus: "upcoming",
      status: "active",
    },
  ],
  drives: [
    {
      id: "drv-1",
      name: "Nimbus Campus Drive 2026",
      companyId: "rec-nimbus",
      date: "2026-08-12",
      venue: "Auditorium A / Online",
      mode: "hybrid",
      eligibleDepartments: ["Computer Science", "Applied Sciences"],
      eligiblePrograms: ["B.Tech Computer Science", "M.Tech Data Science"],
      minCgpa: 7.5,
      maxBacklogs: 0,
      skillsRequired: ["React", "Go", "DSA"],
      registrationDeadline: "2026-08-05",
      status: "upcoming",
    },
    {
      id: "drv-2",
      name: "QuantFin Quant Hiring",
      companyId: "rec-quant",
      date: "2026-07-28",
      venue: "Online",
      mode: "online",
      eligibleDepartments: ["Computer Science", "Business Administration"],
      eligiblePrograms: ["B.Tech Computer Science", "MBA Digital Leadership"],
      minCgpa: 8.0,
      maxBacklogs: 0,
      skillsRequired: ["Python", "Statistics"],
      registrationDeadline: "2026-07-22",
      status: "ongoing",
    },
    {
      id: "drv-3",
      name: "Vertex Design Recruitment",
      companyId: "rec-vertex",
      date: "2026-06-15",
      venue: "Design Lab",
      mode: "offline",
      eligibleDepartments: ["Design Studies"],
      eligiblePrograms: ["UX Design Diploma"],
      minCgpa: 6.5,
      maxBacklogs: 1,
      skillsRequired: ["Figma", "UX"],
      registrationDeadline: "2026-06-08",
      status: "completed",
    },
  ],
  internships: [
    {
      id: "int-1",
      title: "Cloud Engineering Intern",
      companyId: "rec-nimbus",
      duration: "6 months",
      location: "Bengaluru, IN",
      workMode: "hybrid",
      stipend: 45000,
      eligibility: "CSE / Applied Sciences, CGPA 7.5+",
      requiredSkills: ["Go", "Docker", "AWS"],
      deadline: "2026-08-01",
      openPositions: 8,
      status: "open",
    },
    {
      id: "int-2",
      title: "Quant Research Intern",
      companyId: "rec-quant",
      duration: "3 months",
      location: "Mumbai, IN",
      workMode: "office",
      stipend: 60000,
      eligibility: "CSE / BBA, CGPA 8.0+",
      requiredSkills: ["Python", "ML"],
      deadline: "2026-07-20",
      openPositions: 4,
      status: "open",
    },
    {
      id: "int-3",
      title: "Product Design Intern",
      companyId: "rec-vertex",
      duration: "4 months",
      location: "Remote",
      workMode: "remote",
      stipend: 30000,
      eligibility: "Design Studies",
      requiredSkills: ["Figma", "Prototyping"],
      deadline: "2026-06-05",
      openPositions: 3,
      status: "closed",
    },
  ],
  jobs: [
    {
      id: "job-1",
      title: "Software Engineer I",
      companyId: "rec-nimbus",
      salary: 1800000,
      location: "Bengaluru, IN",
      experience: "0-1 years",
      eligibility: "B.Tech CSE, CGPA 7.5+",
      jobType: "full-time",
      deadline: "2026-08-10",
      selectionProcess: ["Aptitude", "Technical", "System Design", "HR"],
      status: "open",
    },
    {
      id: "job-2",
      title: "Quantitative Analyst",
      companyId: "rec-quant",
      salary: 2400000,
      location: "Mumbai, IN",
      experience: "0-2 years",
      eligibility: "CGPA 8.0+",
      jobType: "full-time",
      deadline: "2026-07-26",
      selectionProcess: ["Online Test", "Case Study", "HR"],
      status: "open",
    },
    {
      id: "job-3",
      title: "UX Designer",
      companyId: "rec-vertex",
      salary: 1200000,
      location: "Remote",
      experience: "0-1 years",
      eligibility: "Design portfolio",
      jobType: "full-time",
      deadline: "2026-06-12",
      selectionProcess: ["Portfolio", "Design Challenge", "HR"],
      status: "closed",
    },
    {
      id: "job-4",
      title: "Backend Engineer",
      companyId: "rec-helix",
      salary: 1600000,
      location: "Hyderabad, IN",
      experience: "0-1 years",
      eligibility: "B.Tech CSE",
      jobType: "full-time",
      deadline: "2026-08-18",
      selectionProcess: ["Aptitude", "Technical", "Managerial", "HR"],
      status: "open",
    },
  ],
  applications: [
    { id: "app-1", studentName: "Aarav Sharma", companyId: "rec-nimbus", role: "Software Engineer I", type: "job", department: "Computer Science", cgpa: 8.6, graduationYear: "2026", stage: "interview", appliedDate: "2026-07-10" },
    { id: "app-2", studentName: "Diya Patel", companyId: "rec-quant", role: "Quant Research Intern", type: "internship", department: "Computer Science", cgpa: 9.1, graduationYear: "2026", stage: "shortlisted", appliedDate: "2026-07-12" },
    { id: "app-3", studentName: "Ishaan Verma", companyId: "rec-nimbus", role: "Cloud Engineering Intern", type: "internship", department: "Applied Sciences", cgpa: 7.8, graduationYear: "2026", stage: "assessment", appliedDate: "2026-07-14" },
    { id: "app-4", studentName: "Ananya Gupta", companyId: "rec-vertex", role: "UX Designer", type: "job", department: "Design Studies", cgpa: 8.2, graduationYear: "2025", stage: "offer-accepted", appliedDate: "2026-06-02" },
    { id: "app-5", studentName: "Vivaan Reddy", companyId: "rec-quant", role: "Quantitative Analyst", type: "job", department: "Business Administration", cgpa: 8.9, graduationYear: "2026", stage: "hr-round", appliedDate: "2026-07-15" },
    { id: "app-6", studentName: "Sara Khan", companyId: "rec-helix", role: "Backend Engineer", type: "job", department: "Computer Science", cgpa: 8.0, graduationYear: "2026", stage: "applied", appliedDate: "2026-07-16" },
    { id: "app-7", studentName: "Kabir Singh", companyId: "rec-nimbus", role: "Software Engineer I", type: "job", department: "Computer Science", cgpa: 7.6, graduationYear: "2026", stage: "selected", appliedDate: "2026-07-09" },
    { id: "app-8", studentName: "Meera Nair", companyId: "rec-quant", role: "Quantitative Analyst", type: "job", department: "Computer Science", cgpa: 9.3, graduationYear: "2026", stage: "rejected", appliedDate: "2026-07-11" },
  ],
  interviews: [
    { id: "iv-1", studentName: "Aarav Sharma", companyId: "rec-nimbus", role: "Software Engineer I", date: "2026-07-24", time: "10:30", panel: "Eng Panel A", meetingLink: "https://meet.dreamwave.ai/nimbus-1", venue: "Online", status: "scheduled", feedback: "" },
    { id: "iv-2", studentName: "Vivaan Reddy", companyId: "rec-quant", role: "Quantitative Analyst", date: "2026-07-23", time: "14:00", panel: "Quant Panel", meetingLink: "", venue: "Room 204", status: "scheduled", feedback: "" },
    { id: "iv-3", studentName: "Ananya Gupta", companyId: "rec-vertex", role: "UX Designer", date: "2026-06-08", time: "11:00", panel: "Design Panel", meetingLink: "https://meet.dreamwave.ai/vertex-1", venue: "Online", status: "completed", feedback: "Strong portfolio, offer released." },
  ],
  offers: [
    { id: "off-1", studentName: "Ananya Gupta", companyId: "rec-vertex", role: "UX Designer", department: "Design Studies", salary: 1200000, joiningDate: "2026-07-01", location: "Remote", status: "accepted", expiryDate: "2026-06-20" },
    { id: "off-2", studentName: "Kabir Singh", companyId: "rec-nimbus", role: "Software Engineer I", department: "Computer Science", salary: 1800000, joiningDate: "2026-09-01", location: "Bengaluru, IN", status: "released", expiryDate: "2026-08-15" },
    { id: "off-3", studentName: "Meera Nair", companyId: "rec-quant", role: "Quantitative Analyst", department: "Computer Science", salary: 2400000, joiningDate: "2026-08-01", location: "Mumbai, IN", status: "declined", expiryDate: "2026-07-20" },
  ],
};
