module.exports = {
  ROLES: { USER: 'user', ADMIN: 'admin' },
  PLANS: { FREE: 'free', PRO: 'pro', TEAM: 'team' },
  ORG_TYPES: { INSTITUTION: 'institution', COMPANY: 'company', TEAM: 'team' },
  PORTALS: { STUDENT: 'student', INSTITUTION: 'institution', COMPANY: 'company' },
  INSTITUTION_KINDS: {
    SCHOOL: 'school',
    COLLEGE: 'college',
    UNIVERSITY: 'university',
    OTHER: 'other',
  },
  MEMBER_KINDS: {
    STAFF: 'staff',
    TEACHER: 'teacher',
    STUDENT: 'student',
    RECRUITER: 'recruiter',
  },
  COMPANY_SIZES: ['1-10', '11-50', '51-200', '201-500', '501-1000', '1000+'],
  VERIFICATION_STATUS: ['unverified', 'pending', 'verified', 'rejected'],
  JOB_STATUS: ['draft', 'published', 'archived'],
  WORK_MODES: ['remote', 'hybrid', 'onsite'],
  APPLICATION_STATUS: [
    'applied',
    'reviewing',
    'shortlisted',
    'interview',
    'rejected',
    'hired',
    'withdrawn',
  ],
  ATTENDANCE_STATUS: ['present', 'absent', 'late', 'excused'],
  WEEKDAYS: ['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun'],
  PRIORITIES: ['low', 'medium', 'high'],
  TASK_STATUS: ['todo', 'in_progress', 'done'],
  GOAL_STATUS: ['active', 'completed', 'paused'],
};
