import { Document, Page, Text, View } from '@react-pdf/renderer'
import { getPdfStyles } from './pdfStyles'
import { sanitizeEmojiAndText } from './fonts'

export function PdfDocument({ title = 'Dream Wave Report', author = 'Dream Wave AI', children }) {
  const cleanTitle = sanitizeEmojiAndText(title)
  const cleanAuthor = sanitizeEmojiAndText(author)
  const pdfStyles = getPdfStyles()

  return (
    <Document title={cleanTitle} author={cleanAuthor}>
      <Page size="A4" style={pdfStyles.page}>
        {/* Fixed Top Header */}
        <View style={pdfStyles.header} fixed>
          <Text style={pdfStyles.headerTitle}>DREAM WAVE AI</Text>
          <Text style={pdfStyles.headerSubtitle}>Research & Academic Intelligence</Text>
        </View>

        {/* Dynamic Content */}
        <View style={pdfStyles.content}>
          {children}
        </View>

        {/* Fixed Bottom Footer */}
        <View style={pdfStyles.footer} fixed>
          <Text style={pdfStyles.footerText}>Generated by Dream Wave AI Ecosystem</Text>
          <Text
            style={pdfStyles.pageNumber}
            render={({ pageNumber, totalPages }) => `Page ${pageNumber} of ${totalPages}`}
          />
        </View>
      </Page>
    </Document>
  )
}


export default PdfDocument
