/**
 * Lasya V5 Prompt 9 — Application Copilot + Workspace + Candidate Profile Intelligence
 */

const WORKSPACE_STATUSES = [
  'SAVED',
  'PREPARING',
  'READY',
  'APPLIED',
  'UNDER_REVIEW',
  'INTERVIEW',
  'OFFER',
  'REJECTED',
  'WITHDRAWN',
  'CLOSED',
]

const DOCUMENT_STATUSES = ['ORIGINAL', 'DRAFT', 'APPROVED']

const DOCUMENT_TYPES = ['RESUME', 'COVER_LETTER', 'CERTIFICATE', 'PORTFOLIO_PDF', 'ACADEMIC', 'PROJECT', 'OTHER']

const PROFILE_COMPLETENESS = ['COMPLETE', 'PARTIAL', 'MISSING']

const APPLICATION_HEALTH = ['READY', 'NEEDS_ATTENTION', 'BLOCKED_BY_MISSING_USER_INFORMATION', 'UNKNOWN']

const READINESS_STATES = ['READY', 'NEEDS_IMPROVEMENT', 'INSUFFICIENT_DATA']

const SUBMISSION_STATUSES = ['USER_MARKED_APPLIED', 'VERIFIED_SUBMISSION']

const FUNNEL_STAGES = ['DISCOVERED', 'SAVED', 'PREPARING', 'READY', 'APPLIED', 'INTERVIEW', 'OFFER']

const INJECTION_PATTERNS = [
  /ignore\s+(your|all)\s+rules/i,
  /auto\s*apply/i,
  /submit\s+application/i,
  /bypass\s+authorization/i,
  /fabricate/i,
  /impersonate/i,
]

const WORKFLOW_STAGES = ['DISCOVER', 'REVIEW', 'PREPARE', 'USER_APPROVAL', 'APPLY', 'TRACK']

module.exports = {
  WORKSPACE_STATUSES,
  DOCUMENT_STATUSES,
  DOCUMENT_TYPES,
  PROFILE_COMPLETENESS,
  APPLICATION_HEALTH,
  READINESS_STATES,
  SUBMISSION_STATUSES,
  FUNNEL_STAGES,
  INJECTION_PATTERNS,
  WORKFLOW_STAGES,
}
