/** Lasya V4 Prompt 6 — Campus Ecosystem + Smart Placement Command Center */

const INSTITUTION_HEALTH_STATES = ['HEALTHY', 'ACTIVE', 'NEEDS_ATTENTION', 'INSUFFICIENT_DATA']

const READINESS_CATEGORIES = ['READY', 'NEAR_READY', 'DEVELOPING', 'INSUFFICIENT_DATA']

const SKILL_DEMAND_STATES = ['HIGH_DEMAND', 'AVAILABLE', 'GAP', 'EMERGING', 'UNKNOWN']

const CURRICULUM_ALIGNMENT = ['ALIGNED', 'PARTIALLY_ALIGNED', 'GAP', 'INSUFFICIENT_DATA']

const ALERT_PRIORITIES = ['CRITICAL', 'HIGH', 'MEDIUM', 'LOW']

const PLACEMENT_PIPELINE_STAGES = [
  'ELIGIBLE',
  'APPLIED',
  'SCREENING',
  'SHORTLISTED',
  'ASSESSMENT',
  'INTERVIEW',
  'SELECTED',
  'OFFERED',
  'JOINED',
  'REJECTED',
  'WITHDRAWN',
]

const STAGE_NORMALIZE = {
  applied: 'APPLIED',
  screening: 'SCREENING',
  shortlisted: 'SHORTLISTED',
  assessment: 'ASSESSMENT',
  interview: 'INTERVIEW',
  final_review: 'FINAL_REVIEW',
  selected: 'SELECTED',
  rejected: 'REJECTED',
  withdrawn: 'WITHDRAWN',
  hired: 'JOINED',
  offer_accepted: 'JOINED',
  offer: 'OFFERED',
  offer_extended: 'OFFERED',
}

const CAMPUS_AI_INTENTS = [
  'DAILY_BRIEF',
  'WEEKLY_REPORT',
  'PLACEMENT_FOCUS',
  'SKILL_GAP_ACTION',
  'COMPANY_ENGAGEMENT',
  'STUDENT_SUCCESS',
  'TRAINING_RECOMMENDATION',
  'CURRICULUM_ALIGNMENT',
]

module.exports = {
  INSTITUTION_HEALTH_STATES,
  READINESS_CATEGORIES,
  SKILL_DEMAND_STATES,
  CURRICULUM_ALIGNMENT,
  ALERT_PRIORITIES,
  PLACEMENT_PIPELINE_STAGES,
  STAGE_NORMALIZE,
  CAMPUS_AI_INTENTS,
}
