/** Lasya V4 Prompt 9 — AI Career Copilot + Student Success + Career Roadmap */

const CAREER_STATES = [
  'EXPLORING',
  'BUILDING',
  'PREPARING',
  'APPLYING',
  'INTERVIEWING',
  'PLACEMENT_READY',
  'INSUFFICIENT_DATA',
]

const ROADMAP_PHASES = [
  'FOUNDATION',
  'SKILL_BUILDING',
  'PROJECT_BUILDING',
  'PORTFOLIO',
  'EXPERIENCE',
  'APPLICATION',
  'INTERVIEW',
  'CAREER_ENTRY',
]

const READINESS_LEVELS = [
  'FOUNDATION_READY',
  'PROJECT_READY',
  'APPLICATION_READY',
  'INTERVIEW_READY',
  'INSUFFICIENT_DATA',
]

const RECOMMENDATION_TYPES = [
  'LEARN',
  'BUILD',
  'IMPROVE_PROFILE',
  'APPLY',
  'PREPARE',
  'RESEARCH',
  'NETWORK',
  'REVIEW',
]

const ROADMAP_STEP_STATUS = ['NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', 'BLOCKED']

const PRIORITY_LEVELS = ['HIGH', 'MEDIUM', 'LOW']

const COPILOT_INTENTS = [
  'WHAT_TO_LEARN_NEXT',
  'WHAT_PROJECT_TO_BUILD',
  'WHICH_INTERNSHIP_FITS',
  'WHY_NOT_MATCHING',
  'WHAT_TO_DO_THIS_WEEK',
  'IMPROVE_PROFILE',
  'PRIORITIZE_SKILLS',
  'DAILY_FOCUS',
  'APPLICATION_PREP',
  'INTERVIEW_PREP',
  'EXPLORE_CAREERS',
  'COMPARE_PATHS',
]

const SUPPORT_SIGNAL_TYPES = [
  'INCOMPLETE_PROFILE',
  'NO_PROJECT_EVIDENCE',
  'UPCOMING_DEADLINE',
  'SKILL_GAP',
  'UNFINISHED_ROADMAP_STEP',
]

module.exports = {
  CAREER_STATES,
  ROADMAP_PHASES,
  READINESS_LEVELS,
  RECOMMENDATION_TYPES,
  ROADMAP_STEP_STATUS,
  PRIORITY_LEVELS,
  COPILOT_INTENTS,
  SUPPORT_SIGNAL_TYPES,
}
