/** Lasya V4 Prompt 1 — Unified Ecosystem Intelligence */

const ECOSYSTEM_AI_INTENTS = [
  'ECOSYSTEM_OVERVIEW',
  'INDUSTRY_SKILL_TRENDS',
  'PROGRAM_ALIGNMENT',
  'PARTNERSHIP_INTELLIGENCE',
  'OPPORTUNITY_INTELLIGENCE',
  'RECRUITMENT_PIPELINE',
  'PLACEMENT_OUTCOMES',
  'SKILL_GAP_ANALYSIS',
  'COLLABORATION_GAPS',
]

const MULTI_AGENT_ECOSYSTEM_INTENTS = [
  'IMPROVE_PLACEMENT',
  'STRENGTHEN_PARTNERSHIPS',
  'ALIGN_CURRICULUM',
  'BOOST_PROGRAM_ENGAGEMENT',
]

const ALIGNMENT_LEVELS = ['STRONG_ALIGNMENT', 'GOOD_ALIGNMENT', 'PARTIAL_ALIGNMENT', 'NEEDS_ATTENTION']

const RECOMMENDATION_TYPES = [
  'partnership',
  'program',
  'event',
  'opportunity',
  'workshop',
  'skill_program',
  'project',
  'recruitment',
]

module.exports = {
  ECOSYSTEM_AI_INTENTS,
  MULTI_AGENT_ECOSYSTEM_INTENTS,
  ALIGNMENT_LEVELS,
  RECOMMENDATION_TYPES,
}
