/** Institution RBAC — roles, permissions, admin tags, note types */

const INSTITUTION_ROLES = [
  'OWNER',
  'ADMIN',
  'FACULTY',
  'PLACEMENT_OFFICER',
  'STAFF',
  'VIEWER',
  'RESEARCH_DIRECTOR',
  'INNOVATION_HEAD',
  'INCUBATION_MANAGER',
  'RESEARCH_COORDINATOR',
  'READ_ONLY_REVIEWER',
  'ALUMNI_COORDINATOR',
  'ALUMNI_RELATIONS_DIRECTOR',
  'COMMUNITY_MANAGER',
  'EVENT_MANAGER',
  'VICE_CHANCELLOR',
  'REGISTRAR',
  'DEAN',
  'DIRECTOR',
  'DEPARTMENT_HEAD',
  'QUALITY_ASSURANCE_OFFICER',
  'ANALYTICS_ADMINISTRATOR',
  'READ_ONLY_EXECUTIVE',
]

const INSTITUTION_PERMISSIONS = [
  'students.read',
  'students.manage',
  'students.import',
  'students.export',
  'students.verify',
  'reports.read',
  'reports.generate',
  'analytics.read',
  'placement.manage',
  'documents.read',
  'notes.manage',
  'tags.manage',
  'cohorts.manage',
  'research.read',
  'research.manage',
  'incubation.read',
  'incubation.manage',
  'alumni.read',
  'alumni.manage',
  'executive.read',
  'executive.export',
  'strategic.kpi.read',
  'copilot.read',
]

const ROLE_PERMISSIONS = {
  OWNER: INSTITUTION_PERMISSIONS,
  ADMIN: [
    'students.read',
    'students.manage',
    'students.import',
    'students.export',
    'students.verify',
    'reports.read',
    'reports.generate',
    'analytics.read',
    'placement.manage',
    'documents.read',
    'notes.manage',
    'tags.manage',
    'cohorts.manage',
    'research.read',
    'research.manage',
    'incubation.read',
    'incubation.manage',
    'alumni.read',
    'alumni.manage',
    'executive.read',
    'executive.export',
    'strategic.kpi.read',
    'copilot.read',
  ],
  PLACEMENT_OFFICER: [
    'students.read',
    'students.export',
    'reports.read',
    'reports.generate',
    'analytics.read',
    'placement.manage',
    'documents.read',
    'notes.manage',
    'tags.manage',
  ],
  FACULTY: ['students.read', 'analytics.read', 'reports.read', 'notes.manage', 'research.read', 'research.manage', 'incubation.read', 'incubation.manage', 'alumni.read', 'alumni.manage'],
  STAFF: ['students.read', 'students.import', 'reports.read', 'analytics.read', 'notes.manage', 'research.read', 'incubation.read', 'alumni.read'],
  VIEWER: ['students.read', 'analytics.read', 'reports.read', 'research.read', 'incubation.read', 'alumni.read'],
  RESEARCH_DIRECTOR: [
    'research.read',
    'research.manage',
    'incubation.read',
    'analytics.read',
    'reports.read',
    'reports.generate',
    'documents.read',
    'notes.manage',
  ],
  INNOVATION_HEAD: [
    'research.read',
    'research.manage',
    'incubation.read',
    'incubation.manage',
    'analytics.read',
    'reports.read',
    'reports.generate',
    'documents.read',
    'notes.manage',
  ],
  INCUBATION_MANAGER: [
    'incubation.read',
    'incubation.manage',
    'research.read',
    'analytics.read',
    'reports.read',
    'reports.generate',
    'documents.read',
    'notes.manage',
  ],
  RESEARCH_COORDINATOR: [
    'research.read',
    'research.manage',
    'analytics.read',
    'reports.read',
    'reports.generate',
    'notes.manage',
  ],
  READ_ONLY_REVIEWER: ['analytics.read', 'reports.read', 'research.read', 'incubation.read', 'alumni.read'],
  ALUMNI_COORDINATOR: [
    'alumni.read',
    'alumni.manage',
    'students.read',
    'analytics.read',
    'reports.read',
    'reports.generate',
    'notes.manage',
  ],
  ALUMNI_RELATIONS_DIRECTOR: [
    'alumni.read',
    'alumni.manage',
    'analytics.read',
    'reports.read',
    'reports.generate',
    'documents.read',
    'notes.manage',
  ],
  COMMUNITY_MANAGER: [
    'alumni.read',
    'alumni.manage',
    'analytics.read',
    'reports.read',
    'notes.manage',
  ],
  EVENT_MANAGER: [
    'alumni.read',
    'alumni.manage',
    'analytics.read',
    'reports.read',
    'notes.manage',
  ],
  VICE_CHANCELLOR: [
    'executive.read',
    'analytics.read',
    'reports.read',
    'reports.generate',
    'executive.export',
    'strategic.kpi.read',
    'copilot.read',
    'students.read',
    'research.read',
    'incubation.read',
    'alumni.read',
  ],
  REGISTRAR: [
    'executive.read',
    'analytics.read',
    'reports.read',
    'reports.generate',
    'executive.export',
    'strategic.kpi.read',
    'students.read',
    'students.manage',
    'alumni.read',
  ],
  DEAN: [
    'executive.read',
    'analytics.read',
    'reports.read',
    'strategic.kpi.read',
    'copilot.read',
    'students.read',
    'research.read',
    'alumni.read',
  ],
  DIRECTOR: [
    'executive.read',
    'analytics.read',
    'reports.read',
    'reports.generate',
    'strategic.kpi.read',
    'students.read',
    'research.read',
    'incubation.read',
    'placement.manage',
  ],
  DEPARTMENT_HEAD: [
    'executive.read',
    'analytics.read',
    'reports.read',
    'strategic.kpi.read',
    'students.read',
    'notes.manage',
  ],
  QUALITY_ASSURANCE_OFFICER: [
    'executive.read',
    'analytics.read',
    'reports.read',
    'reports.generate',
    'executive.export',
    'strategic.kpi.read',
    'students.read',
    'documents.read',
  ],
  ANALYTICS_ADMINISTRATOR: [
    'executive.read',
    'analytics.read',
    'reports.read',
    'reports.generate',
    'executive.export',
    'strategic.kpi.read',
    'copilot.read',
    'students.read',
    'research.read',
    'incubation.read',
    'alumni.read',
    'placement.manage',
  ],
  READ_ONLY_EXECUTIVE: [
    'executive.read',
    'analytics.read',
    'reports.read',
    'strategic.kpi.read',
    'copilot.read',
    'students.read',
    'research.read',
    'incubation.read',
    'alumni.read',
  ],
}

const ADMIN_TAGS = [
  'Placement Ready',
  'Training Required',
  'Resume Missing',
  'Certificate Pending',
  'Project Verified',
  'Document Incomplete',
]

const NOTE_TYPES = [
  'internal',
  'placement',
  'academic_followup',
  'counselling',
  'verification',
  'administrative',
]

const REPORT_TYPES = [
  'student_directory',
  'department',
  'program',
  'placement',
  'skills',
  'projects',
  'certificates',
  'academic_summary',
  'profile_completeness',
  'attendance',
]

function roleHasPermission(role, permission) {
  const perms = ROLE_PERMISSIONS[role] || []
  return perms.includes(permission)
}

module.exports = {
  INSTITUTION_ROLES,
  INSTITUTION_PERMISSIONS,
  ROLE_PERMISSIONS,
  ADMIN_TAGS,
  NOTE_TYPES,
  REPORT_TYPES,
  roleHasPermission,
}
