/**
 * Lasya V5 Prompt 1 — Autonomous Ecosystem Orchestration + Multi-Agent Collaboration
 * Agent registry, tool registry, risk classification, orchestration intents.
 */

const RISK_LEVELS = ['LOW_RISK', 'MEDIUM_RISK', 'HIGH_RISK', 'CRITICAL']

const STEP_STATUSES = ['PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'SKIPPED', 'BLOCKED']

const EXECUTION_STATUSES = [
  'DRAFT',
  'PLANNING',
  'WAITING_APPROVAL',
  'RUNNING',
  'COMPLETED',
  'FAILED',
  'CANCELLED',
  'SIMULATION',
]

const AGENT_STATUSES = ['AVAILABLE', 'DEGRADED', 'DISABLED', 'ERROR']

const ORCHESTRATION_LIMITS = {
  MAX_DEPTH: 5,
  MAX_STEPS: 12,
  MAX_HANDOFFS: 8,
  TIMEOUT_MS: 60000,
  MAX_RETRIES: 2,
}

const TOOL_DEFINITIONS = {
  READ_CAREER_PROFILE: {
    toolId: 'READ_CAREER_PROFILE',
    name: 'Read career profile',
    purpose: 'Load authorized career goals, skills, and readiness',
    riskLevel: 'LOW_RISK',
    sideEffects: false,
    permissions: ['student'],
  },
  SEARCH_OPPORTUNITIES: {
    toolId: 'SEARCH_OPPORTUNITIES',
    name: 'Search opportunities',
    purpose: 'Find matching opportunities from canonical marketplace',
    riskLevel: 'LOW_RISK',
    sideEffects: false,
    permissions: ['student', 'institution', 'company'],
  },
  ANALYZE_SKILLS: {
    toolId: 'ANALYZE_SKILLS',
    name: 'Analyze skills',
    purpose: 'Skill gap and evidence analysis',
    riskLevel: 'LOW_RISK',
    sideEffects: false,
    permissions: ['student', 'institution'],
  },
  ANALYZE_PLACEMENT: {
    toolId: 'ANALYZE_PLACEMENT',
    name: 'Analyze placement pipeline',
    purpose: 'Placement funnel and readiness metrics',
    riskLevel: 'LOW_RISK',
    sideEffects: false,
    permissions: ['institution'],
  },
  ANALYZE_PARTNERSHIP: {
    toolId: 'ANALYZE_PARTNERSHIP',
    name: 'Analyze partnerships',
    purpose: 'Partnership health and collaboration intelligence',
    riskLevel: 'LOW_RISK',
    sideEffects: false,
    permissions: ['institution', 'company'],
  },
  ANALYZE_PROGRAM: {
    toolId: 'ANALYZE_PROGRAM',
    name: 'Analyze programs',
    purpose: 'Program-industry alignment intelligence',
    riskLevel: 'LOW_RISK',
    sideEffects: false,
    permissions: ['institution'],
  },
  ANALYZE_ANALYTICS: {
    toolId: 'ANALYZE_ANALYTICS',
    name: 'Analyze ecosystem metrics',
    purpose: 'Executive and BI analytics consumption',
    riskLevel: 'LOW_RISK',
    sideEffects: false,
    permissions: ['institution', 'company'],
  },
  CREATE_TASK: {
    toolId: 'CREATE_TASK',
    name: 'Create task',
    purpose: 'Create internal review or preparation task',
    riskLevel: 'MEDIUM_RISK',
    sideEffects: true,
    permissions: ['student', 'institution', 'company'],
  },
  PREPARE_NOTIFICATION: {
    toolId: 'PREPARE_NOTIFICATION',
    name: 'Prepare notification',
    purpose: 'Prepare in-app notification preview — not sent automatically',
    riskLevel: 'MEDIUM_RISK',
    sideEffects: false,
    permissions: ['institution', 'company'],
  },
  PREPARE_EMAIL: {
    toolId: 'PREPARE_EMAIL',
    name: 'Prepare email',
    purpose: 'Prepare email preview — requires approval before send',
    riskLevel: 'HIGH_RISK',
    sideEffects: false,
    permissions: ['institution', 'company'],
  },
  CREATE_WORKFLOW: {
    toolId: 'CREATE_WORKFLOW',
    name: 'Create workflow',
    purpose: 'Create approval-gated workflow from template',
    riskLevel: 'MEDIUM_RISK',
    sideEffects: true,
    permissions: ['institution', 'company'],
  },
  GENERATE_REPORT: {
    toolId: 'GENERATE_REPORT',
    name: 'Generate report',
    purpose: 'Generate internal analytics report preview',
    riskLevel: 'LOW_RISK',
    sideEffects: false,
    permissions: ['institution', 'company'],
  },
}

const AGENT_DEFINITIONS = {
  CAREER_AGENT: {
    agentId: 'CAREER_AGENT',
    name: 'Career Agent',
    description: 'Career goals, readiness, gaps, and personalized plans',
    capabilities: ['career_analysis', 'skill_gaps', 'roadmap'],
    allowedTools: ['READ_CAREER_PROFILE', 'ANALYZE_SKILLS', 'CREATE_TASK'],
    requiredPermissions: ['student'],
    riskLevel: 'LOW_RISK',
    readDomains: ['career_profile', 'skills', 'projects', 'opportunities'],
    writeDomains: ['career_recommendations'],
    externalActions: [],
  },
  OPPORTUNITY_AGENT: {
    agentId: 'OPPORTUNITY_AGENT',
    name: 'Opportunity Agent',
    description: 'Discover, filter, analyze, and recommend opportunities',
    capabilities: ['opportunity_search', 'marketplace', 'matching'],
    allowedTools: ['SEARCH_OPPORTUNITIES', 'ANALYZE_SKILLS'],
    requiredPermissions: ['student', 'institution', 'company'],
    riskLevel: 'LOW_RISK',
    readDomains: ['opportunities', 'applications'],
    writeDomains: [],
    externalActions: [],
  },
  PLACEMENT_AGENT: {
    agentId: 'PLACEMENT_AGENT',
    name: 'Placement Agent',
    description: 'Placement pipeline, deadlines, and readiness alerts',
    capabilities: ['placement_analysis', 'deadline_alerts'],
    allowedTools: ['ANALYZE_PLACEMENT', 'PREPARE_NOTIFICATION', 'CREATE_WORKFLOW'],
    requiredPermissions: ['institution'],
    riskLevel: 'MEDIUM_RISK',
    readDomains: ['placements', 'applications', 'interviews'],
    writeDomains: ['placement_tasks'],
    externalActions: [],
  },
  PARTNERSHIP_AGENT: {
    agentId: 'PARTNERSHIP_AGENT',
    name: 'Partnership Agent',
    description: 'Partnership analysis and collaboration proposal preparation',
    capabilities: ['partnership_analysis', 'proposal_draft'],
    allowedTools: ['ANALYZE_PARTNERSHIP', 'PREPARE_EMAIL', 'CREATE_WORKFLOW'],
    requiredPermissions: ['institution', 'company'],
    riskLevel: 'MEDIUM_RISK',
    readDomains: ['partnerships', 'companies', 'projects'],
    writeDomains: ['proposal_drafts'],
    externalActions: ['PREPARE_EMAIL'],
  },
  INSTITUTION_AGENT: {
    agentId: 'INSTITUTION_AGENT',
    name: 'Institution Agent',
    description: 'Institution capabilities and ecosystem overview',
    capabilities: ['institution_analysis'],
    allowedTools: ['ANALYZE_ANALYTICS', 'ANALYZE_PROGRAM'],
    requiredPermissions: ['institution'],
    riskLevel: 'LOW_RISK',
    readDomains: ['institution', 'programs', 'departments'],
    writeDomains: [],
    externalActions: [],
  },
  PROGRAM_AGENT: {
    agentId: 'PROGRAM_AGENT',
    name: 'Program Agent',
    description: 'Program alignment and industry skill coverage',
    capabilities: ['program_alignment'],
    allowedTools: ['ANALYZE_PROGRAM', 'GENERATE_REPORT'],
    requiredPermissions: ['institution'],
    riskLevel: 'LOW_RISK',
    readDomains: ['programs', 'skills'],
    writeDomains: [],
    externalActions: [],
  },
  ANALYTICS_AGENT: {
    agentId: 'ANALYTICS_AGENT',
    name: 'Analytics Agent',
    description: 'Evidence-based metrics, trends, and decision support',
    capabilities: ['analytics', 'trends', 'decision_support'],
    allowedTools: ['ANALYZE_ANALYTICS', 'GENERATE_REPORT'],
    requiredPermissions: ['institution', 'company'],
    riskLevel: 'LOW_RISK',
    readDomains: ['metrics', 'trends', 'reports'],
    writeDomains: [],
    externalActions: [],
  },
  WORKFLOW_AGENT: {
    agentId: 'WORKFLOW_AGENT',
    name: 'Workflow Agent',
    description: 'Convert approved plans into workflow executions',
    capabilities: ['workflow_planning', 'workflow_creation'],
    allowedTools: ['CREATE_WORKFLOW', 'CREATE_TASK'],
    requiredPermissions: ['institution', 'company', 'student'],
    riskLevel: 'MEDIUM_RISK',
    readDomains: ['workflows'],
    writeDomains: ['workflow_executions'],
    externalActions: [],
  },
  NOTIFICATION_AGENT: {
    agentId: 'NOTIFICATION_AGENT',
    name: 'Notification Agent',
    description: 'Prepare notification previews according to policy',
    capabilities: ['notification_prepare'],
    allowedTools: ['PREPARE_NOTIFICATION'],
    requiredPermissions: ['institution', 'company'],
    riskLevel: 'MEDIUM_RISK',
    readDomains: ['notifications'],
    writeDomains: [],
    externalActions: [],
  },
  LEARNING_AGENT: {
    agentId: 'LEARNING_AGENT',
    name: 'Learning Agent',
    description: 'Recommend skill-building and learning paths',
    capabilities: ['learning_recommendations'],
    allowedTools: ['ANALYZE_SKILLS', 'CREATE_TASK'],
    requiredPermissions: ['student'],
    riskLevel: 'LOW_RISK',
    readDomains: ['learning', 'skills'],
    writeDomains: ['learning_recommendations'],
    externalActions: [],
  },
}

const ORCHESTRATION_INTENTS = {
  PREPARE_INTERNSHIP: {
    id: 'PREPARE_INTERNSHIP',
    description: 'Find internships and identify improvement areas',
    roles: ['student'],
    agents: ['CAREER_AGENT', 'OPPORTUNITY_AGENT', 'LEARNING_AGENT'],
    requiresApproval: false,
  },
  PARTNERSHIP_PROPOSAL: {
    id: 'PARTNERSHIP_PROPOSAL',
    description: 'Prepare company collaboration proposal',
    roles: ['institution'],
    agents: ['PARTNERSHIP_AGENT', 'INSTITUTION_AGENT', 'PROGRAM_AGENT', 'ANALYTICS_AGENT'],
    requiresApproval: true,
  },
  PLACEMENT_DEADLINE: {
    id: 'PLACEMENT_DEADLINE',
    description: 'Analyze placement deadline and prepare alerts',
    roles: ['institution'],
    agents: ['PLACEMENT_AGENT', 'OPPORTUNITY_AGENT', 'NOTIFICATION_AGENT'],
    requiresApproval: true,
  },
  PROGRAM_ALIGNMENT_REVIEW: {
    id: 'PROGRAM_ALIGNMENT_REVIEW',
    description: 'Review program-industry alignment',
    roles: ['institution'],
    agents: ['ANALYTICS_AGENT', 'PROGRAM_AGENT', 'OPPORTUNITY_AGENT', 'WORKFLOW_AGENT'],
    requiresApproval: true,
  },
  EXECUTIVE_DECISION: {
    id: 'EXECUTIVE_DECISION',
    description: 'Decision support from ecosystem analytics',
    roles: ['institution', 'company'],
    agents: ['ANALYTICS_AGENT', 'WORKFLOW_AGENT'],
    requiresApproval: false,
  },
  FIND_OPPORTUNITIES: {
    id: 'FIND_OPPORTUNITIES',
    description: 'Find matching career opportunities',
    roles: ['student'],
    agents: ['CAREER_AGENT', 'OPPORTUNITY_AGENT'],
    requiresApproval: false,
  },
}

const ACTION_POLICY = {
  READ_CAREER_PROFILE: { risk: 'LOW_RISK', approval: 'NO_APPROVAL' },
  SEARCH_OPPORTUNITIES: { risk: 'LOW_RISK', approval: 'NO_APPROVAL' },
  ANALYZE_SKILLS: { risk: 'LOW_RISK', approval: 'NO_APPROVAL' },
  PREPARE_EMAIL: { risk: 'HIGH_RISK', approval: 'REQUIRED' },
  PREPARE_NOTIFICATION: { risk: 'MEDIUM_RISK', approval: 'USER_CONFIRMATION' },
  CREATE_WORKFLOW: { risk: 'MEDIUM_RISK', approval: 'USER_CONFIRMATION' },
  CREATE_TASK: { risk: 'MEDIUM_RISK', approval: 'NO_APPROVAL' },
}

module.exports = {
  RISK_LEVELS,
  STEP_STATUSES,
  EXECUTION_STATUSES,
  AGENT_STATUSES,
  ORCHESTRATION_LIMITS,
  TOOL_DEFINITIONS,
  AGENT_DEFINITIONS,
  ORCHESTRATION_INTENTS,
  ACTION_POLICY,
}
