/**
 * Lasya V5 Prompt 8 — Opportunity Intelligence 2.0 + Smart Matching + Application Strategy
 */

const OPPORTUNITY_TYPES = [
  'JOB',
  'INTERNSHIP',
  'FELLOWSHIP',
  'SCHOLARSHIP',
  'HACKATHON',
  'COMPETITION',
  'RESEARCH_OPPORTUNITY',
  'PROJECT_OPPORTUNITY',
  'EVENT',
]

const SOURCE_TYPES = ['OFFICIAL', 'VERIFIED', 'PARTNER', 'USER_SUBMITTED', 'INTERNAL', 'UNKNOWN']

const FRESHNESS_STATES = ['ACTIVE', 'EXPIRED', 'UNKNOWN', 'CLOSED']

const MATCH_STATES = ['STRONG_MATCH', 'MATCH', 'PARTIAL_MATCH', 'LOW_MATCH', 'INSUFFICIENT_DATA']

const SKILL_CATEGORIES = ['REQUIRED', 'PREFERRED', 'DEMONSTRATED', 'IN_PROGRESS', 'MISSING', 'UNKNOWN']

const READINESS_STATES = ['READY_TO_CONSIDER', 'NEEDS_IMPROVEMENT', 'INSUFFICIENT_DATA']

const APPLICATION_STATUSES = ['SAVED', 'PREPARING', 'APPLIED', 'INTERVIEW', 'OFFER', 'REJECTED', 'WITHDRAWN', 'CLOSED']

const FEED_CATEGORIES = ['FOR_YOU', 'DEADLINES_SOON', 'SKILL_MATCHES', 'NEW', 'SAVED', 'APPLIED', 'ARCHIVED']

const INJECTION_PATTERNS = [
  /ignore\s+(your|all)\s+rules/i,
  /bypass\s+authorization/i,
  /auto\s*apply/i,
  /submit\s+application/i,
  /guarantee\s+(job|hire|selection)/i,
  /fabricate/i,
  /impersonate/i,
]

const WORKFLOW_STAGES = ['DISCOVER', 'REVIEW', 'PREPARE', 'USER_APPROVAL', 'APPLY', 'TRACK']

module.exports = {
  OPPORTUNITY_TYPES,
  SOURCE_TYPES,
  FRESHNESS_STATES,
  MATCH_STATES,
  SKILL_CATEGORIES,
  READINESS_STATES,
  APPLICATION_STATUSES,
  FEED_CATEGORIES,
  INJECTION_PATTERNS,
  WORKFLOW_STAGES,
}
