/** Lasya V4 Prompt 7 — Partnership Intelligence + Collaboration Hub */

const PARTNERSHIP_FIT_LEVELS = [
  'STRONG_FIT',
  'GOOD_FIT',
  'PARTIAL_FIT',
  'LOW_FIT',
  'INSUFFICIENT_DATA',
]

const PARTNERSHIP_HEALTH_STATES = [
  'ACTIVE',
  'HEALTHY_ACTIVITY',
  'LOW_ACTIVITY',
  'EXPIRING',
  'INSUFFICIENT_DATA',
]

const COLLABORATION_TYPES = [
  'PLACEMENT',
  'INTERNSHIP',
  'RESEARCH',
  'INDUSTRY_PROJECT',
  'TRAINING',
  'EVENT',
  'FACULTY_DEVELOPMENT',
  'CURRICULUM',
  'INNOVATION',
  'INCUBATION',
]

const PARTNERSHIP_AI_INTENTS = [
  'PARTNER_MATCH',
  'COLLABORATION_BRIEF',
  'PROPOSAL_DRAFT',
  'RENEWAL_REVIEW',
  'PARTNERSHIP_HEALTH',
  'ACTIVITY_SUMMARY',
]

const PROPOSAL_STATES = ['DRAFT', 'REVIEW', 'APPROVAL', 'READY_TO_SEND']

module.exports = {
  PARTNERSHIP_FIT_LEVELS,
  PARTNERSHIP_HEALTH_STATES,
  COLLABORATION_TYPES,
  PARTNERSHIP_AI_INTENTS,
  PROPOSAL_STATES,
}
