/** Lasya V4 Prompt 3 — Institution + Company + Program Intelligence */

const ALIGNMENT_LEVELS = ['ALIGNED', 'PARTIALLY_ALIGNED', 'GAP', 'INSUFFICIENT_DATA']

const ENGAGEMENT_STATUSES = ['ACTIVE', 'RECENT', 'LOW_ACTIVITY', 'INACTIVE', 'INSUFFICIENT_DATA']

const EVIDENCE_TYPES = [
  'DECLARED',
  'VERIFIED',
  'PROJECT_EVIDENCED',
  'CURRENTLY_LEARNING',
  'INFERRED',
  'UNKNOWN',
]

const INTELLIGENCE_AI_INTENTS = [
  'INSTITUTION_SUMMARY',
  'COMPANY_SUMMARY',
  'PROGRAM_ALIGNMENT',
  'SKILL_GAP_ANALYSIS',
  'INDUSTRY_TRENDS',
  'CURRICULUM_RECOMMENDATION',
  'COMPANY_RECOMMENDATIONS',
]

module.exports = {
  ALIGNMENT_LEVELS,
  ENGAGEMENT_STATUSES,
  EVIDENCE_TYPES,
  INTELLIGENCE_AI_INTENTS,
}
