/**
 * Lasya V5 Prompt 4 — Research Workspace + Knowledge Synthesis + Report Builder
 */

const WORKSPACE_STATUSES = ['DRAFT', 'RESEARCHING', 'SYNTHESIZING', 'REVIEW', 'COMPLETED', 'ARCHIVED']

const SOURCE_TYPES = [
  'DOCUMENT',
  'BOOK',
  'PAPER',
  'WEB_SOURCE',
  'INSTITUTION',
  'COMPANY',
  'OPPORTUNITY',
  'PROJECT',
  'COURSE',
  'NOTE',
  'STRUCTURED_RECORD',
]

const AUTHORITY_LEVELS = ['OFFICIAL', 'CANONICAL', 'VERIFIED', 'USER_PROVIDED', 'GENERAL', 'UNKNOWN']

const CLAIM_TYPES = ['FACT', 'SYNTHESIS', 'INFERENCE', 'RECOMMENDATION']

const CLAIM_STATUSES = ['SUPPORTED', 'UNSUPPORTED', 'CONTRADICTED', 'PENDING']

const REPORT_STATUSES = ['DRAFT', 'REVIEW', 'APPROVED', 'REJECTED']

const REPORT_TEMPLATES = [
  'ACADEMIC_RESEARCH',
  'BUSINESS_RESEARCH',
  'CAREER_RESEARCH',
  'INDUSTRY_ANALYSIS',
  'INSTITUTION_REPORT',
  'PROGRAM_REPORT',
  'COMPANY_REPORT',
  'PLACEMENT_REPORT',
  'PARTNERSHIP_REPORT',
]

const REPORT_SECTIONS = [
  'TITLE',
  'RESEARCH_QUESTION',
  'EXECUTIVE_SUMMARY',
  'BACKGROUND',
  'METHODOLOGY',
  'KEY_FINDINGS',
  'EVIDENCE',
  'SOURCE_COMPARISON',
  'LIMITATIONS',
  'RESEARCH_GAPS',
  'RECOMMENDATIONS',
  'REFERENCES',
  'APPENDIX',
]

const TIMELINE_EVENTS = [
  'WORKSPACE_CREATED',
  'SOURCE_ADDED',
  'SOURCE_REMOVED',
  'FINDING_GENERATED',
  'SYNTHESIS_COMPLETED',
  'REPORT_GENERATED',
  'REPORT_REVIEWED',
  'REPORT_APPROVED',
  'SOURCE_UPDATED',
]

const INJECTION_PATTERNS = [
  /ignore\s+(your|all)\s+rules/i,
  /bypass\s+authorization/i,
  /expose\s+private/i,
  /modify\s+permissions/i,
]

module.exports = {
  WORKSPACE_STATUSES,
  SOURCE_TYPES,
  AUTHORITY_LEVELS,
  CLAIM_TYPES,
  CLAIM_STATUSES,
  REPORT_STATUSES,
  REPORT_TEMPLATES,
  REPORT_SECTIONS,
  TIMELINE_EVENTS,
  INJECTION_PATTERNS,
}
