/** Lasya V4 Prompt 2 — Advanced Placement + Talent Intelligence */

const READINESS_STATES = [
  'READY',
  'NEARLY_READY',
  'PREPARING',
  'NEEDS_ATTENTION',
  'INSUFFICIENT_DATA',
]

const MATCH_CATEGORIES = [
  'STRONG_MATCH',
  'GOOD_MATCH',
  'PARTIAL_MATCH',
  'LOW_MATCH',
  'INELIGIBLE',
  'INSUFFICIENT_DATA',
]

const ELIGIBILITY_RESULTS = ['ELIGIBLE', 'INELIGIBLE', 'UNKNOWN', 'NEEDS_REVIEW']

const EVIDENCE_TYPES = [
  'verified_skill',
  'certificate',
  'project',
  'shared_skill',
  'programming_language',
  'learning',
  'program',
  'internship',
  'research',
  'event',
]

const STUDENT_AI_INTENTS = [
  'CAREER_READINESS',
  'OPPORTUNITY_MATCH',
  'SKILL_GAPS',
  'LEARNING_PREP',
  'PROJECT_EVIDENCE',
  'APPLICATION_STATUS',
  'IMPROVE_PLACEMENT',
]

const COMPANY_AI_INTENTS = [
  'ROLE_CANDIDATES',
  'SKILL_TRENDS',
  'PROGRAM_ALIGNMENT',
  'FUNNEL_ANALYSIS',
  'TALENT_POOL',
]

const INSTITUTION_AI_INTENTS = [
  'INDUSTRY_DEMAND',
  'SKILL_DISTRIBUTION',
  'PLACEMENT_PIPELINE',
  'PROGRAM_ALIGNMENT',
  'ELIGIBLE_STUDENTS',
]

const MULTI_AGENT_TALENT_INTENTS = [
  'IMPROVE_STUDENT_PLACEMENT',
  'MATCH_CANDIDATES_TO_ROLE',
  'CLOSE_SKILL_GAPS',
]

module.exports = {
  READINESS_STATES,
  MATCH_CATEGORIES,
  ELIGIBILITY_RESULTS,
  EVIDENCE_TYPES,
  STUDENT_AI_INTENTS,
  COMPANY_AI_INTENTS,
  INSTITUTION_AI_INTENTS,
  MULTI_AGENT_TALENT_INTENTS,
}
