/** Lasya V4 Prompt 5 — Talent Marketplace + Matching */

const PROFILE_COMPLETENESS_LEVELS = ['COMPLETE', 'GOOD', 'PARTIAL', 'INCOMPLETE']

const APPLICATION_READINESS_STATES = ['READY', 'NEEDS_IMPROVEMENT', 'INCOMPLETE', 'NOT_ELIGIBLE']

const MATCH_RESULTS = [
  'STRONG_MATCH',
  'GOOD_MATCH',
  'PARTIAL_MATCH',
  'LOW_MATCH',
  'NOT_ELIGIBLE',
  'INSUFFICIENT_DATA',
]

const OPPORTUNITY_STATUS_LABELS = {
  draft: 'DRAFT',
  open: 'OPEN',
  published: 'OPEN',
  active: 'OPEN',
  closing_soon: 'CLOSING_SOON',
  closed: 'CLOSED',
  paused: 'PAUSED',
  filled: 'FILLED',
  cancelled: 'CANCELLED',
  archived: 'CLOSED',
}

const MARKETPLACE_AI_INTENTS = [
  'OPPORTUNITY_RECOMMENDATION',
  'APPLICATION_READINESS',
  'MATCH_EXPLANATION',
  'SKILL_GAP_FOR_ROLE',
  'WHICH_INTERNSHIP',
]

const RECRUITER_MATCH_INTENTS = [
  'MATCH_TALENT_TO_ROLE',
  'ROLE_SKILL_GAPS',
  'FUNNEL_DROP_OFF',
]

module.exports = {
  PROFILE_COMPLETENESS_LEVELS,
  APPLICATION_READINESS_STATES,
  MATCH_RESULTS,
  OPPORTUNITY_STATUS_LABELS,
  MARKETPLACE_AI_INTENTS,
  RECRUITER_MATCH_INTENTS,
}
